### ISSUE TITLE
Download button on hover is not displayed

### ISSUE THREAD

**Issue by youk** [eight04/image-picka#101]
Thank you for a nice extension. On some sites, however, the hover button is not displayed. I guess those work with images in more dynamic way.

Take for example [https://www.muziekweb.nl/Link/CAX15648/Pr%C3%A9ludes-du-2e-livre](https://www.muziekweb.nl/Link/CAX15648/Pr%C3%A9ludes-du-2e-livre). No button on the thumbnail or the enlarged images. I can see the covers when I use the Pick Images from Current Tab though.

Is this possible to fix?

**Comment by youk** [comment]
Well, I understand the image in under an overlay and providing a generic solution could be tricky.

Still, would it be possible to fix per site? Like a piece of configuration (provided by user) that would define where to display the hover button: CSS selector or JavaScript function (don't know if the latter is possible to use).

**Comment by eight04** [comment]
> a piece of configuration (provided by user) that would define where to display the hover button: CSS selector or JavaScript function

I think it wouldn't work. Suppose the hover button is displayed on the `.buttons` layer, the extension still have to find out which image needs to be downloaded when the button is clicked, which can't be detected when something covers on the image.

**Comment by youk** [comment]
Another user-provided CSS selector for the image to download? The simplest one for that site would be `.covers img[class=active]`.

**Comment by eight04** [comment]
It would only work if the image has a unique selector. A counterexample:
https://codepen.io/anon/pen/rreYPO

**Comment by youk** [comment]
Um? Are we still discussing per-site configuration? The above selector for the site in question is unambiguous and matches only one image.

**Comment by eight04** [comment]
Yes, we are discussing a "per-site" configuration, and the image in your example does have a unique selector. However, I don't want to create a configuration that would work on "specific site" only.

If you need some features that would only work on muziekweb.nl, I suggest creating a userscript to handle it.

**Comment by youk** [comment]
`.covers img[class=active]` is a unique selector which, for that HTML, applies to a single image only. Because there is only one image being displayed at a time.

I obviously was not talking about a configuration for a particular site. A was talking about a generic facility, so that users can define their own configurations whichever they want. Is that really hard to understand?

Anyways, if you are not interested, there is nothing to discuss. Thanks for your time.

**Comment by eight04** [comment]
I do understand. Feel free to open a new issue if there is any idea to solve this.
