### ISSUE TITLE
Download button is HUGE!

### ISSUE THREAD

**Issue by jedikalimero** [eight04/image-picka#104]
The download button that hovers over individual images is really huge!
All the customization options for this button are great since you can customize the position and the delay in appearing/disappearing, but you can't customize the size. If I prefer to have it in a discrete 20x20 pixels size, I can't do it.

Customization of the colours of this button would be great too (but not so neccesary).

**Comment by eight04** [comment]
Good point. Users would probably want to change the button size depending on their screen size.

**Comment by jedikalimero** [comment]
Yes. And you need to be aware that the icon will hover on any picture, making it very dificult to click on thumbnails like the ones in Google Images (see attached example)

![captura de pantalla 2018-07-30 17 10 41](https://user-images.githubusercontent.com/18701653/43409365-a08a88ee-941b-11e8-9121-27d6f70e2657.png)
