### ISSUE TITLE
Please, incorporate as much options as possible from preQuantum add on "Save Images"

### ISSUE THREAD

**Issue by jedikalimero** [eight04/image-picka#105]
Hi,
I like this add on very much but I miss some of the options that make famous the pre Quantum Add On called "Save Images" by Lumox: https://addons.mozilla.org/es/firefox/addon/save-images/

This add-on, like image-picka had a lot of filters for the images like sixe, image dimensions, regular expressions and also file types (JPG, GIF, PNG, SVG, WEBP and BMP)

Instead of having separate options for saving images from "current tab + rigth tabs" and just "Right tabs", it haves a configuration option to indicate if including the current tab or not when saving right tabs. This simplifies the interface the user sees usually since this option mostly depends on the way the user uses Firefox and he will choose almost always the same option.

But the feature I miss the most is the hability to open links, image links or just the links selected (or image links) in new tabs (and also in a single new tab by using frames). When using this options (from the context menu), a dialog box appeared with a list of all the links so you could unselect some of them before actually performing the action

**Comment by eight04** [comment]
> this option mostly depends on the way the user uses Firefox and he will choose almost always the same option

There are some cases that the `pageTitle` matters. Images downloaded by each command would be saved into a different folder. I think I will keep both of them in the contextmenu.

> open links, image links or just the links selected (or image links) in new tabs (and also in a single new tab by using frames)

It doesn't sound like a feature for image downloader. Are you looking for something like these?

* https://addons.mozilla.org/es/firefox/addon/open_links_in_tabs/?src=search
* https://addons.mozilla.org/es/firefox/addon/ya-open-selected-links/?src=search
* https://addons.mozilla.org/es/firefox/addon/open-multiple-urls/?src=search
* https://addons.mozilla.org/es/firefox/addon/open-selected-links/?src=search

**Comment by jedikalimero** [comment]
Mmmm... yes, you're right. I think Lumox included it so you can open all those URLs as tabs and then use "Save images from tabs to the right".

I'm already using an extension called SnapLinks that opens all URLs inside a selection rectangle. It is not exactly the same but it usually provides the same result.

Anyway, I discovered Lumox finally created a webextension compatible version of Save Images called Simage https://addons.mozilla.org/es/firefox/addon/simage/ that also has this feature. It has some limitations due to the webextension restrictions but it works for me :-)
