### ISSUE TITLE
Preventing formation of illegal file names.

### ISSUE THREAD

**Issue by jedikalimero** [eight04/image-picka#106]
Using PageTitle to compose the name of the file to be saved is sometimes great because you obtain an image with a name in context and not just something like '**10.jpg**' (that usually becomes something like '**10(43).jpg**' 😉). But sometimes the title can contain characters that can be ilegal for a filename, or a diagonal bar ( '**\\**' or '**\/**' ) that can generate an unwanted new folder.

I don't know if you have taken this into account in **batch download** but I have seen it fail for **single image download**. More precisely when saving an image on its own, not embedded in an HTML file. In this precise case, the PageTitle is the URL of the image, even with URL variables followed by '**?**': '**http://whatever.wh/whatever/whatever.jpg?var1=121&var2=bob**')

ImagePicka notifies an illegal name and the file is not saved. I think a better approach would be to replace automatically the offending characters with dashes or something like that and remove any URL variables. Or even, in the case of saving an image on its own (so the page does not have a real title), also remove the leading '**HTTP://**' and file extension (because it would be duplicated)

**Comment by eight04** [comment]
We have already escaped the variable:
https://github.com/eight04/image-picka/blob/ec7f12bbd65d77b27f441e48b79a1e5605b571c6/extension/background/background.js#L590-L602

Could you post the actual URL that throws the error?

**Comment by jedikalimero** [comment]
Sorry for not answering back before, but I lost the URL of the image that failed and I couldn't find it. Anyway, here is another URL where the Add on fails to create a "legal" name:

http://img108.imagevenue.com/img.php?image=232494651_z0014_123_184lo.jpg

When I click the Download hovering button, I get ar error message:
filename must not contain illegal characters
url: http://img108.imagevenue.com/img.php?image=232494651_z0014_123_184lo.jpg
filename: 232494651_z0014_123_184lo.jpg

My filename pattern in single download is ${pageTitle} ${name}${ext}
I use this pattern bacause most of the time I download images called just 024.jpg or something like that and this doesn't give any clue of where the image came from or what/who represents. But this information can be usually found in the title of the page (althoug this particular example is not the case).

In this case, since the HTML/PHP file does not define a <TITLE>, the title of the page is the same as the URL, including variables. I don't know exactly why this image fails since the error doesn't give any clue of what name it was trying to create. But I think it has to do with the presence of illegal characters for a filename in the ${pageTitle} variable (not in the ${pageUrl} variable that I assume is correctly escaped). Obviously this behaviour happens when the page doesn't have a title so the title of the tab is automatically the same as the URL.

I think a more sensible behaviour would be:

1- When the tab contains an image on its own (not inside a HTML, PHP or whatever container, just the image in the image viewer) and the filename pattern contains ${pageTitle}, remove ${pageTitle} and substitute it with ${pageUrl} (unless ${pageUrl} is already present in the expression to avoid duplicity). This way, the URL and path is added to the filename and this can contain the reference information the user expected to preserve when including ${pageTitle} in the expression (most probably in a folder of the path). 
As a side note, this treatment will also avoid ending up having file names like: 
232494651_z0014_123_184lo.jpg (JPEG Image, 1218 × 1504 pixels) - Escaled (71 %) 232494651_z0014_123_184lo.jpg
where "232494651_z0014_123_184lo.jpg (JPEG Image, 1218 × 1504 pixels) - Escaled (71 %)" is the title of the tab.

2- When a page has no title (so the tab title is the URL), treat the image as it would be treated if the image were on its own (and so what I described in the previous point is applied).

**Comment by jedikalimero** [comment]
I just noticed if I use ${pageTitle}${name}${ext} instead of ${pageTitle} ${name}${ext} (notice the space), then the image is saved with just the filename and extension.

However, As I explained in the previous message, this is not what I intended since the file name may not contain desired context information for the image. In the given example, the image url does not contain any useful context information anyway, but many times a subfolder in the path of the image can contain useful information.

**Comment by eight04** [comment]
The problem is that the filename could not contain leading spaces. Since `pageTitle` is empty, the result would be `" filename.ext"`.

So there are actually 2 problems:

1. Leading/trailing spaces should be removed. We need a `trimSpaces` function around here:
    https://github.com/eight04/image-picka/blob/2759244b8d58c6c49ab63b7322637ed26b698375/extension/background/background.js#L655-L662
2. When `${pageTitle}` is empty, it should fallback to the URL.

**Comment by eight04** [comment]
> When ${pageTitle} is empty, it should fallback to the URL.

I think we need a second thought about this. If we change it then users will never be able to detect whether `pageTitle` is empty when using expressions e.g.
```
${pageTitle || pageHostname}
```
I'll revert this change.

**Comment by jedikalimero** [comment]
I'm not sure but I believe this expression becomes pageTitle when pageTitle is not empty or pageHostname when pageTitle is empty.
I think this should be default behavior or even better the full path (so information about folder containing the images is included, not just the host name)

Usually all images in a gallery are contained in a folder of their own and most of the time this folder is named as the gallery (the person, object or event depicted )

**Comment by jedikalimero** [comment]
Anyway, that expression only makes sense because there is the possibility that the title is empty. In the same way, the user really doesn't want to know if the title is empty or not (what use would this be?). In any case what the user just is aware of this possibility in order to deal with it by using such expression but if we replace an empty title with something else, then there is no need for the user to use such expression.

On the other hand, leaving the things as the are gives the user the possibility to replace an empty title with what they want by using an expression instead of being limited to what the add on replaces. The thing is to be able to have that control, the user has to know he has that control. I didn't know it when I suggested the replacement.
