### ISSUE TITLE
Add option to download a numbered series of images

### ISSUE THREAD

**Issue by jedikalimero** [eight04/image-picka#114]
Here is an easy to implement feature that would make Image Picka become one of the best add ons for saving images.

Many times, when you want to save a series of images, they all have the same name (and same URL) just changing an index number.
At present, using Image Picka, if you find a thumbnail gallery and you want to save all the images in the gallery, you have to middle click every thumbnail to open the full image in a new tab. With every single image (or you can use an add on like Snap Links Plus to do the hard work for you) and then you can use Image Picka to save the images in the tabs to the right. Fortunately Image Picka has many options to filter the images you want to save from other images in those tabs (usually of smaller size) but you have to open every image in a tab. Imagine a gallery with 150 images. You have to open 150 tabs!

Or, alternatively, you could open just the first image and tell Image Picka to find all the images in that series by inspecting the URL and assuming the rightmost number in the name is an index, so Image Picka would create a pick gallery with all the images in the series ready to save all at once in just one tab.

Just imagine I am displaying in my browser image 9 of a series of 15. The new tab should be populated with images 1 to 15 (or 0 to 14). if there is no image 5, just jump it and search for image 4 so you can continue the series even if some loose images are missing. you can adjust how many images to jump before considering you have reached the end of the series. If the series is very long, you could limit the gallery to 255 images after the original one or something like that (then, if you started in image 1 and ended in image 256, then the user could use image 256 to generate a new gallery that starts in 256 and ends in 512 and so on). Also, if the images are too big in size (since they are not thumbnails but full size images), you could add a simple button that reduces all images to fit the width of the window or just shows them in thumbnail mode.

Add the item to generate the gallery not only to the toolbar button but also in the context menu of images embedded in a webpage if they have a number in the name. This way, if the user is looking at a full size image in a gallery but this image is not alone but embedded in a web page, the user does not need to use "view image" to isolate it in order for the gallery generator to work on it.

There is currently an add on called **Images Quicky** that allows you to navigate and save a series of images but it just provides you with forward and backward buttons and a save button and you have to navigate the images manually. It also has problems with number sequences with leading zeros and doesn't navigate to the beginning in case the index of the first image is 0 instead of 1 (or 000 instead of 001).

There was, prior to Quantum another add on called **Show Me More**  (https://addons.mozilla.org/en-US/firefox/addon/show-me-more/) that worked exactly as I just described so it is not a new idea, but the last update of this add on was more than 7 years ago so it is very unlikely it will be ever ported to Quantum.

**Comment by eight04** [comment]
Could you post the URL of the gallery? It sounds like this problem could be solved with the [transformation feature](https://github.com/eight04/image-picka#transform-url-with-regexp).

**Comment by jedikalimero** [comment]
It is not a specific gallery. Just any series of pictures indexed by a number in the file name.

Here is an example gallery (NSFW but nothing gross):
http://dbnaked.com/pictures/content/general/sites/pinupfiles/53950_pinup_files_set_243/
If you click on the first thumbnail, the full image will appear on a layer above the page. (in other galleries it will just open a new page containing the full size image, usually with "next/previous/return to gallery" links or directly the image alone). 

The url of the image is:
http://dbnaked.com/pictures/content/general/sites/pinupfiles/53950_pinup_files_set_243/1.jpg
(in this case the path before the file name is the same as the gallery page but this is not always the case. Also, the file name could be something like pinup1.jpg, 001.jpg or pinup1_fullsize.jpg, so **Image Picka** may need to identify the number inside the filename)

The URL of the next image is the same but with 2 as the number instead of 1 and so on up to 12

My proposal is, when you have the full image in display and right click on it, a new option in the **Image Picka** submenu would be something like: "_Show full series of the image in a new tab_" and then, a new tab would open showing all the 12 images one below the other so you can save them individually (maybe using the hovering image download button) or all of them by using "_Pick Images from Current Tab_". the original add on **Show Me More** only worked with images that are alone (not inside a page) because it used a toolbar button, but using a right click menu option you can overcome this limitation and address the desired image even if it is inside a web page.

You could also generate the picker page directly (so the new option would be something like "_Pick all series from this image_"), but in this case, you wouldn't be able to see the pictures full size as **Show Me More** does.

You need to have in mind that some image series use leading zeros (01, 02, 03... 09, 10, 11, 12) and some others not (1, 2, 3... 9, 10, 11, 12) , so, in case the image the user selects is 10.jpg and when going backwards **Image Picka** can't find 9.jpg, it should also try with 09.jpg.

Also, some image series begin with 0 instead of 1

And finally, some image series may have some image missing, so when you reach a number that does not find any image, you should try the next number before assuming this is the end of the series just in case one image is missing. You can set this jump to 1 missing image, 2 missing images... or let the user set it in the options.

Yet another finally: if **Image Picka** finds an image called 17384.jpg, you don't want it to generate a page with 17384 (or more) images. So you should set a limit of images **Image Picka** will search in huge series. I think 256 should be ok.

**Comment by eight04** [comment]
In the example:
```
// thumbnail URL
http://dbnaked.com/pictures/content/general/sites/pinupfiles/53950_pinup_files_set_243/thumb_1.jpg
// full image URL
http://dbnaked.com/pictures/content/general/sites/pinupfiles/53950_pinup_files_set_243/1.jpg
```
So you can create a transform rule:
```
http://dbnaked\.com/pictures/content/general/sites/pinupfiles/([^/]+)/thumb_(.+)
http://dbnaked.com/pictures/content/general/sites/pinupfiles/$1/$2
```
It would remove `thumb_` from the URL so Image Picka can download the full-size image when you download the thumbnail.

> in this case the path before the file name is the same as the gallery page but this is not always the case. Also, the file name could be something like pinup1.jpg, 001.jpg or pinup1_fullsize.jpg,

Any example?

> Show full series of the image in a new tab" and then, a new tab would open showing all the 12 images one below the other ...

There are some addons work like this:

* [Re-Pagination - WebExtension fork](https://addons.mozilla.org/en-US/firefox/addon/re-pagination-webext-fork/)
* [uAutoPagerize](https://addons.mozilla.org/en-US/firefox/addon/uautopagerize/?src=search)

**Comment by jedikalimero** [comment]
Sorry for taking so long to reply.

> So you can create a transform rule:

> http://dbnaked\.com/pictures/content/general/sites/pinupfiles/([^/]+)/thumb_(.+)
> http://dbnaked.com/pictures/content/general/sites/pinupfiles/$1/$2

> It would remove thumb_ from the URL so Image Picka can download the full-size image when you download the thumbnail.

Yes, you could, but if you need to go to the add-on to create a new rule every time you want to download a gallery, you are missing the conveninece of using an Add-on whose mission is to make things easy, not more complicated.

Re-Pagination add-on sort of works by making one continuous page with all the pages in the series one after the other. It does not work when the thumbnail opens directly the image or when there are no "next" button or when the "next" button is in javascript. It is definitely not the solution

**Comment by eight04** [comment]
There is an option "Detect image URLs from links" which can be used here. However, since the website protects their images with referer check, the image doesn't load. Currently I'm working on it.
