### ISSUE TITLE
Image failed to Download from konachan.com

### ISSUE THREAD

**Issue by temporalix** [eight04/image-picka#122]
When trying to download images from "konachan.com" certain images fail to download.

I have 2 examples that fail 100% of the time for me, but work fine if the image is saved using "save image as".

http://konachan.com/post/show/257333/flowers-forest-grass-landscape-makkou_4-moon-night

http://konachan.com/post/show/253462/animal-bird-clouds-dress-landscape-logo-long_hair-

tried multiple combinations of settings, download from cache, escaping special characters, etc.

**Comment by eight04** [comment]
I can download these images without problems.

Please provide more information. Error message? Browser version?

**Comment by temporalix** [comment]
With a bit of testing i've found my issue.
The Filename pattern was :
imgboardpics/${pageTitle}-${name}${ext}

tried the method with fallback for pageTitle:
imgboardpics/${pageTitle||pageUrl}-${name}${ext}

file saves as : "undefined - Konachan.com - 257333 flowers forest grass landscape makkou_4 moon night nobody original scenic stars tree watermark"

removed pageTitle and file saves as : "http：／／konachan.com／post／show／257333／flowers-forest-grass-landscape-makkou_4-moon-night - Konachan.com - 257333 flowers forest grass landscape makkou_4 moon night nobody original scenic stars tree watermark"

there might be a need to either handle the undefined value of pageTitle some way or force a fallback because a filename pattern like : 
"Image Picka/${pageTitle}/${index-1} - ${name}${ext}"

would also fail when pageTitle doesn't exist.

**Comment by eight04** [comment]
I can download those images with your filename pattern on Windows 7. Could you provide more information e.g. operating system, browser version, Image Picka version, and the error message?

Also, how did you download the image? By drag-n-drop or the browser button?

> "Image Picka/${pageTitle}/${index-1} - ${name}${ext}"
> 
> would also fail when pageTitle doesn't exist.

On Windows, this would be converted into something like `Image Picka//0 - blablbla.jpg`, which is a valid path.

In fact, the title of the page is not empty on my browser:
![image](https://user-images.githubusercontent.com/1324510/45563894-4b64f680-b881-11e8-8ac1-9323e9c2bb06.png)

**Comment by temporalix** [comment]
was originally going to post those details until i tried a different filename pattern.

Windows 10 Version	10.0.17134 Build 17134
Firefox 60.2.0esr (64-bit)
Image picka 0.8.5

Don't get any error messages in the console.

The image just doesn't download and you see the following in the downloads window

![filesaveerror](https://user-images.githubusercontent.com/4292979/45564189-f65cbc80-b84f-11e8-8f48-9a8ae737ebb5.PNG)

**Comment by eight04** [comment]
I think the problem is that the length of the entire file path is too long. Try to cut down the value of `Max length of the filename` option.

**Comment by temporalix** [comment]
max length of a path is 255 though from what i've read. 

the base path length to the folder(including folder name) is 25.
the name is 116 characters long and the page title is 143 characters long, so just those 2 together exceed path length limit.

the Max length of the file name  was set to 128. also tried increasing it to just under the max possible at 220.
maybe  the max length limit isn't trimming the filename to the limit, if that's what it should do?

**Comment by eight04** [comment]
In fact, that option defines the max length of a variable in the filename pattern. When the variable is too long, it is trimmed to match specified length.

Yeah I know that is not how it is described in its title. I think someone had raised this problem before, but I keep forgetting to change it.

**Comment by temporalix** [comment]
sounds good in principle, but i'd hate to be the user that wants to add all the different variables for their filename. other than changing how the limit works, is it not possible to use each individual piece and sum them together and display an error?

**Comment by eight04** [comment]
Do you mean to calculate the length of the file path before sending it to Firefox's download manager? I'm not sure if it works, maybe we have to know the length of the prefix (i.e. the default download folder of Firefox).

**Comment by temporalix** [comment]
I found something that might help, you should be able to get the download directory path using this : pref.get("browser.download.dir") ? its in the preferences if that's accessible.   

then you can take the non variable part of filename pattern (sub-folder) to get a base length and use it together with the filename to show and error.

to test this locally you could make a folder with a really long name and you should in theory get the same issues.

**Comment by eight04** [comment]
Extensions can't access `about:config` directly, unless they are exposed by the webextension API [`browserSettings`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings).

**Comment by eight04** [comment]
BTW, does setting `Max length of the filename` to 30 or less solve the problem?

**Comment by temporalix** [comment]
yes that allows it to download. read bug logs and they don't plan to ever expose absolute path. 
The best way to deal with the issue would be to try handle the error from the catch, if there is an error, otherwise there isn't much that could be done.

**Comment by eight04** [comment]
Move to #124.
