### ISSUE TITLE
image preview slider

### ISSUE THREAD

**Issue by secretuser** [eight04/image-picka#125]
Love your extension, thanks for the updates.
Can you maybe adjust the max slider height to a larger number? 
because it's really inconvenient for certain use cases to have it locked at 200px. 
currently I use a bookmarklet to adjust it to 1000px, but I feel that's really a bandaid that should be in the extension.
Anyway thx for reading

**Comment by eight04** [comment]
I wonder how do you select images when they are displayed in 1000px height? It is even larger than the screen size of some laptops.

**Comment by secretuser** [comment]
1000px is merely a suggestion, I work with vertical and horizontal setups
for monitors and for some images that's really handy to have, also it's an
adjustable slider anyway, so say 800px is also fine, or some other number.

**Comment by eight04** [comment]
I guess I will add a new option to specify the max value of the slider, which defaults to `200`.
