### ISSUE TITLE
Batch download shouldn't use `saveAs` option

### ISSUE THREAD

**Issue by Hisboilroi** [eight04/image-picka#139]
Since the upgrade, I no longer get a batch save when I click "Save" in Image Picka.  Instead I get a separate Windows "Save As" page for each image, which I then have to save individually.

**Comment by eight04** [comment]
Yeah batch download shouldn't use `saveAs` option:
https://github.com/eight04/image-picka/blob/dc4baa70c39241b3510a365c386c27ef69356654/extension/background/background.js#L407
