### ISSUE TITLE
filename problem

### ISSUE THREAD

**Issue by circcc** [eight04/image-picka#149]
filename problem.

when I download a image(starwars lego) with image-picka from this link:

http://gall.dcinside.com/board/view/?id=aviationfight&no=173421&page=1

filename is wrong "viewimage.php_id=2cabd927f1db37a868b6d1bd02&no=29bcc427bd8777a16fb3dab004c86b6fe0f25512895f218cee112a072de13719034a9a12382288641". proper filename is "1511319103.jpg".

I know it is by WE limitation.

but, QuickDrag WE (https://addons.mozilla.org/en-US/firefox/addon/quickdrag-we/)" workaround this problem with showing save window when drag image to download. so, I don't use image-picka anymore to download single image.

image-picka can do it too?

**Comment by eight04** [comment]
QuickDrag WE uses a link to trigger download:
https://github.com/kanap0nta/QuickDrag-WE/blob/bee4d34dd9378d9f7668b41a2f3d6b1c829d6aae/Firefox/quickdrag.js#L200-L206

Maybe we can try to extract the filename from the response header.

**Comment by eight04** [comment]
I've implemented this in #151. Currently, it only works with cached images. If the image is not cached, the download will fail.
