### ISSUE TITLE
I can't save images from staticflickr.com.

### ISSUE THREAD

**Issue by fernicar** [eight04/image-picka#150]
I can't save images from staticflickr.com.
source of some examples tested on different tabs:
https://c1.staticflickr.com/5/4059/4336736350_4143ac601e.jpg
https://www.flickr.com/photos/42639790@N08/4336736350

win 10, fox 63 and updated addon.
screenshot: https://dc624.4shared.com/img/dqmUnMqgee/s23/16737be4a48/staticflickr

**Comment by eight04** [comment]
Is there any error in the console of the batch download page?

**Comment by fernicar** [comment]
Error: "Failed to load: https://c1.staticflickr.com/5/4059/4336736350_4143ac601e.jpg" icker.js:310:5
load/< moz-extension://9c64b2a1-e1b2-4ac6-bbe5-0920515b4d41/picker/picker.js:310:5

> 
> 
> Is there any error in the console of the batch download page?

Error: "Failed to load: https://c1.staticflickr.com/5/4059/4336736350_4143ac601e.jpg" icker.js:310:5
load/< moz-extension://9c64b2a1-e1b2-4ac6-bbe5-0920515b4d41/picker/picker.js:310:5

**Comment by fernicar** [comment]
A new firefox profile with the addon works fine, something in my main profile must be breaking your addon. It will take me some time to diagnose what is it. Tell me if you have any idea of the culprit.

**Comment by eight04** [comment]
I think this issue has been fixed in NoScript v10.2.0. Can you verify?

**Comment by fernicar** [comment]
> 
> 
> I think this issue has been fixed in NoScript v10.2.0. Can you verify?

Afirmative, NoScript v10.2.0 update doesn't reproduce same error/behavior.
Thank you for let me know about the update news.
