### ISSUE TITLE
(Feature Request) default save locations

### ISSUE THREAD

**Issue by AlexanderEvans** [eight04/image-picka#160]
While I love the text based file name expressions(especially the index option), I wanted to request a way to save bulk images into a specific folder more easily than having to constantly change the pattern path.  Could you add support for a few default locations so we can sort our images by the type of image rather than the source more easily?  Maybe even add it to right click on images like: https://addons.mozilla.org/en-US/firefox/addon/save-image-in-folder-ex/  I actually currently use this, but it can't even figure out how to use the right extension and stopped receiving updates a year ago.  And they don't support dynamic filename patterns.  Maybe this could also be done by adding a drop down arrow button to switch between preset filename patterns for the bulk DL.

**Comment by eight04** [comment]
> sort our images by the type of image rather than the source

Do you mean the extension of the image i.e. `jpg/gif/png`?

> preset filename patterns for the bulk DL.

Currently, we record the history of the filename pattern. If you have used different patterns multiple times, it will display a "recently used" list for you:
![image](https://user-images.githubusercontent.com/1324510/49693780-74163700-fbb7-11e8-9e51-ae1271c07600.png)
