### ISSUE TITLE
(Feature Request) random charachters

### ISSUE THREAD

**Issue by AlexanderEvans** [eight04/image-picka#161]
While the dateString is great for generating unique filenames, I was wondering if you could generate a unique random number instead, that doesn't encode time information?  Or even create a hash so that the date is obfuscated.  It would be really nice for websites that just rename everything to "xlarge.png" without adding information about when the file was saved to the image.  Otherwise maybe a global index variable that increments between individual saves as well as batch saves?  And have a way to just manually set it to an integer if the extension is uninstalled at some point?  That could be a really clean solution.

**Comment by eight04** [comment]
> generate a unique random number

Try enabling simple expression and use something like `{String(Math.random()).slice(2,9)}` in the filename.

But I don't think it is a good idea. Why not put the date information in the filename?
