### ISSUE TITLE
(Question) 单张图片保存时的进度提示

### ISSUE THREAD

**Issue by ordinarier** [eight04/image-picka#162]
eight04兄，您好
在保存单张图片的时候，没有像批量保存一样给出任何提示，这样的话不是太清楚是否有保存下来
是不是可以采用类似批量保存一样的弹出提示，或让保存按钮变个色之类的显性化提醒

另，我用的操作系统是osx 10.14
ff版本是Quantum 63.03

**Comment by eight04** [comment]
目前的單張下載按鈕的確不太直觀。我想在按下去時加個淡出動畫會比較好。
不過這樣其實不算是進度提示，因為動畫發生於「下載開始」而非「下載結束」。
而且無法作用於拖拉下載等不會用到按鈕的情況。

> 类似批量保存一样的弹出提示

這指的是什麼？我印象中，批量保存不會彈出任何關於下載進度的提示。

**Comment by ordinarier** [comment]
对，不是进度提示，就是提示开始下载
其实这也够了，下载进度不是一定必要的

**Comment by eight04** [comment]
#165 加入按鈕動畫。

提醒一點︰在勾選了「從快取中取得圖片」選項的情況下，因為快取必須在該頁面開啟時才能取得，若按下按鈕後立即關閉頁面，是有可能下載失敗的。
