### ISSUE TITLE
sugestion

### ISSUE THREAD

**Issue by rygastan** [eight04/image-picka#166]
Hi thx for the appli. Works fine at this moment, but a little thing, if you can add it, will be good. When I save a Photo, the soft answer me where, because I choose and indicate it in prefs. But if I change the folder where to save in the "save window",in usage, instead of what I specifies in prefs, when I save a new photo, It returns to the folder specified in prefs... I would be pleased to be able to save by it reoppen in last folder automatiquely if I want to change, and at least it will 'save' this new folder for the next time. So, I hope I explain rightly what it is missed for now for me. If the option already exist in prefs or possible, I dont find how and/or where to activate in it.

**Comment by eight04** [comment]
Duplicate of #15.
