### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by GiRaFa-SM** [eight04/image-picka#18]
I dont know if this suggestions are possible now, since webextensions doesnt have all funcionalites that XUL had but. 

It's possible to add a feature to choose to only save images in the left or right tabs? Currently it seems that it process all images in all tabs.
The second suggestion is: it's possible to set a minimum filesize in the batch save window? this way we could filter what we really want. 

My other suggestion which i'm sure it's not possible now is, The XUL image picker has a feature that saves all images in the same folder if they're in the same webpage. In sites like 4chan or reddit this saves a lot of time. It's possible and/or complicated to add a feature like this? Thank you for the addon, it's really good to see functional addons like these in FF57.

**Comment by eight04** [comment]
> choose to only save images in the left or right tabs

To download images from right tabs (includes current tab):

1. Right click on toolbar button, click "From tabs to the right".
2. Enable the context menu and right click on the page, select "Image Picka" > "From Tabs to The Right".

> set a minimum filesize in the batch save

I think it is possible to do this, but it has to download the image again to get filesize. I'll see if this worth it.

> saves all images in the same folder if they're in the same webpage

I'm not sure what did you mean. Isn't that how batch download works?

**Comment by GiRaFa-SM** [comment]
Enable the context menu and right click on the page, select "Image Picka" > "From Tabs to The Right".

I dont know your policy about this, imo it's duplicating functions, it's something nice to have but i dont really know how complicated or if its possible to "improve" this.

In the XUL image picker, we had an dedicated shortcut/button to choose automatically images from the right, is that possible to implement now? In the way it works it's already functional, but having options isnt something bad exactly.

"I'm not sure what did you mean. Isn't that how batch download works?"

I should've specified what i mean here, if you have used the XUL Version from ImagePicker, when you click to save an image by dragging or alt+click, it asks you to save in an directory, if you continue saving images from the same page, it downloads the image without confirmation dialog and in the same folder you saved previously.  If you change to another page and press alt+click for example, it'll ask again where to save.

If you have an fork like WaterFox (FF55), download it and test image picker and try do what i said, i can record a video comparing both if you want too/or dont have time to get a grasp of what i'm talking about.

**Comment by eight04** [comment]
> an dedicated shortcut/button to choose automatically images from the right/left

So what you are asking is to pick images from tabs to the right when the toolbar button is clicked, right? Sounds like to customize the default command of toolbar button.

> when you click to save an image by dragging or alt+click, it asks you to save in an directory

This can be done by turning "Ask me where to save the image" on.

> if you continue saving images from the same page, it downloads the image without confirmation dialog and in the same folder

This is impossible with webextensions. When downloading without confirmation dialog, extensions can only download the image into default download folder.

However, if you just want to put downloaded images in a same folder when they are downloaded from the same tab, you can turn **off** "save as..." dialog and set the filename pattern to something like:
```
${pageTitle}/${name}${ext}
```
Then, images would be saved in a subfolder whose name equals to page title. Hence, images grabbed from the same tab are placed in the same folder.

**Comment by eight04** [comment]
Move to #21, #22.

**Comment by GiRaFa-SM** [comment]
Thank you for adding these features.

"Then, images would be saved in a subfolder whose name equals to page title. Hence, images grabbed from the same tab are placed in the same folder." 

Its not the way i wanted, but it's okay for me, thank you.
