### ISSUE TITLE
Follow thumbnails to original image

### ISSUE THREAD

**Issue by PhoenixIV** [eight04/image-picka#189]
Hi there, reading issue https://github.com/eight04/image-picka/issues/9 there seems to be a very manual way of receiving images in other sizes derived via urls. I have no idea how to access this feature, by the way.

However, I came up with the idea to have a button that replaces (or adds) images to the overview that are linked from images on the site. It is likely an image that links to an image will be the same, but full size version of this image.

I imagine to have a button in the selection overview to access this feature. The user can then decide to replace images with linked images or add the linked images. Even tough I doubt that the latter will be used a lot.

Thanks

**Comment by eight04** [comment]
One problem is that the link may lead to another different image so a simple option might not work well. We need a way to allow users to preview the link target.

**Comment by PhoenixIV** [comment]
I derived the idea from my own use-case: I often use this plugin to download images from galeries. For those I can be certain that every image I click leads to the original. So whatever creative solutions pop up on your side, it would be handy for me to just follow all "image-links" on request. The "add" (instead of replace) option targets users who need embedded **and** linked images.

**Comment by eight04** [comment]
For example, your avatar is a link which leads to your profile. In order to know whether the link target is an image, the extension has to load the URL and check the file type, causing extra network traffic.

BTW, are you talking about batch download or downloading a single image?

**Comment by PhoenixIV** [comment]
> the extension has to load the URL and check the file type, causing extra network traffic.
For sure. I guess if it is on the user's request it is fine, tough.

I talk about batch-downloading.
