### ISSUE TITLE
保存阿里系图片小图换大图的正则表达式

### ISSUE THREAD

**Issue by jiyun** [eight04/image-picka#190]
https://sc01.alicdn.com/kf/HTB167HkX2vsK1RjSspdq6AZepXaG/MF23-Sexy-Arabic-Lady-Evening-Dresses-2018.jpg_50x50.jpg
上面的图例 是常见的阿里系保存格式
50 * 50 的小图
原图就是 去掉链接尾部的 _50x50.jpg 大概是 _\d{2,4}x\d{2,4}\.\w{3}
https://sc01.alicdn.com/kf/HTB167HkX2vsK1RjSspdq6AZepXaG/MF23-Sexy-Arabic-Lady-Evening-Dresses-2018.jpg
类似的淘宝 天猫 等阿里系网站都这样处理图片
请教这里的替换正则表达式如何书写

**Comment by yfdyh000** [comment]
`(.+)(_\d{2,4}x\d{2,4}.\w{3})`
`$1`

推荐 https://regexr.com/

**Comment by jiyun** [comment]
# ali
(.+)(_\d{2,4}x\d{2,4}.\w{3})\S{2}\w{4}|(_\d{2,4}x\d{2,4}.\w{3})|(_.\w{4})
$1
根据ali 的图片规律加强了匹配规则 
感谢楼上的指导
