### ISSUE TITLE
Problem installing the addon in Chromium and Opera on Xubuntu

### ISSUE THREAD

**Issue by paradoxseeker** [eight04/image-picka#193]
Hello.

I try this because Firefox change this addons conditions of use again and a lot of my addons didn't work for now.
So I try to install this addon on Chromium (Versión 74.0.3729.108) and Opera (Versión:58.0.3135.65). The two web browsers shows the same error in the code of the package.json. (PD: Also I create a copy of the package.json, rename it manifest.json and add in the first line of the code "manifest_version": 2 for Opera, and show the same error)

The errors are:
Unrecognized manifest key 'dependencies'.
    "dependencies": {
    "@eight04/idb-storage": "^0.4.1",
    "content-disposition-bundle": "github:eight04/content-disposition-bundle",
    "expression-eval-bundle": "github:eight04/expression-eval-bundle",
    "webext-menus": "^0.1.3",
    "webextension-polyfill": "^0.4.0"
  },

Unrecognized manifest key 'devDependencies'.
 "devDependencies": {
    "eslint": "^5.16.0",
    "mime": "^2.4.2",
    "node-sigint": "0.0.1",
    "shelljs": "^0.8.3",
    "shx": "^0.3.2",
    "stream-throttle": "^0.1.3",
    "sync-version": "^1.0.1",
    "web-ext": "^3.0.0",
    "webext-tx-fix": "^0.3.1"
  }

Unrecognized manifest key 'license'.
  "license": "MIT",

Unrecognized manifest key 'scripts'.
"devDependencies": {
    "eslint": "^5.16.0",
    "mime": "^2.4.2",
    "node-sigint": "0.0.1",
    "shelljs": "^0.8.3",
    "shx": "^0.3.2",
    "stream-throttle": "^0.1.3",
    "sync-version": "^1.0.1",
    "web-ext": "^3.0.0",
    "webext-tx-fix": "^0.3.1"
  }

Unrecognized manifest key 'title'.
"title": "Image Picka",

Maybe this is because the code of Opera and Chromium are a little different of Google Chrome? 
I use Xubuntu, but I don't think this is the cause of the problem.

**Comment by eight04** [comment]
Why do you want to rename `package.json` to `manifest.json`? If you want to install the repository as an unpacked extension:
https://github.com/eight04/image-picka#chrome

**Comment by eight04** [comment]
Ouch, it seems that [the tutorial](https://developer.chrome.com/extensions/getstarted#manifest) told you to create a new `manifest.json`. You don't have to since we already have one in the `extension` folder.

**Comment by eight04** [comment]
I have changed the tutorial link to https://stackoverflow.com/a/49769909/3413125.
