### ISSUE TITLE
Tor Browser requires verification

### ISSUE THREAD

**Issue by Dirk-K** [eight04/image-picka#194]
Image Picka used to work fine in Tor browser until the latest update [8.0.8 (based on Mozilla Firefox 60.6.1esr) (64-Bit), Mac OS X]. Now Tor deactivates Image Picka automatically and refuses to verify the add-on.

**Comment by eight04** [comment]
Does it relate to the CA expiration bug?
https://bugzilla.mozilla.org/show_bug.cgi?id=1548973
