### ISSUE TITLE
Feature for download images from page text links to images

### ISSUE THREAD

**Issue by MurzNN** [eight04/image-picka#195]
Please add feature to download images from links on page. For implement this will be good to add checkbox "Parse links on page with filter" and via regex filters like `/image-folder/.*\.jpg` users will can filter and select needed images.

**Comment by eight04** [comment]
Do you have an example page?

**Comment by MurzNN** [comment]
Here https://murznn.github.io/image-links-example.html is quick example

**Comment by eight04** [comment]
Sounds like we can have an option: `Detect image URLs from links`.

This may also fix #189, the difference is that the URL must look like an image i.e. `*.jpg`, `*.png`, etc.

It should work fine with batch download.

For single-download, there are some problems:

1. Single-download is triggered by mouse gesture, which may conflict with other link-related operation.
2. If there is an image which is a child node of a link, which element should be used?

I think we can implement this option for batch download first.

**Comment by eight04** [comment]
@PhoenixIV Any idea?

**Comment by PhoenixIV** [comment]
1. You mean something like ctrl/shift/alt + click? I think it is safe to assume that user will choose a trigger that is not also used by another task.
2. Make it a setting.

Yes, having an 'Detect image URLs from links' option would also solve https://github.com/eight04/image-picka/issues/189, indeed.

Thanks for reaching out! :)

**Comment by MurzNN** [comment]
Single download are easily solved via build-in "Save link as" item, so in extension most useful function is mass downloading. And only your extension normally works with url filter and Cyrillic letters in url! All other extensions can filter only by filename and size.
