### ISSUE TITLE
found unexpected key 'browser_style'

### ISSUE THREAD

**Issue by fengjingzhun** [eight04/image-picka#198]
**Steps:**

  1) download zip file
  2) unzip zip file
  3) load an unpacked extension

**Error:**

   found unexpected key 'browser_style'
```
...
	"manifest_version": 2,
...
```
   Unrecognized manifest key 'applications'.
```
...
        "applications": {
		"gecko": {
			"id": "image-picka@eight04.blogspot.com"
		}
	},
...
```

**Version:**

   Google Chrome 74.0.3729.169 （64bit）CN

   Windows 10

   image-picka-0.10.1.zip

**Comment by eight04** [comment]
It's a warning that Chrome doesn't recognize these fields inside manifest. It won't affect the functionality.
