### ISSUE TITLE
All Image Selection Functions Not Working

### ISSUE THREAD

**Issue by brazenvoid** [eight04/image-picka#205]
Continuation from my review:
```
It used to work great but since a few months the picker does not pick any images, all fail. Dragging images yield corrupt files of some 100-200 bytes size.
Only with the option "try download from browser cache" fixes the drag and double click image save. Picker remains broken.
```
As requested by the dev on Mozilla addons site:
```
Please report the URL/extension version to Github issue tracker: https://github.com/eight04/image-picka/issues. We have observed some issues with the content blocking feature in the newest Firefox.
```
Yes, I use a custom blocking profile with strict and more alongside uMatrix and uBlock Origin filtration. The extension version is v0.11.1. As suggested to provide links but I experience it everywhere really. 

I have since switched to another addon for bulk image downloads with similar view of your picker. But am still stuck with yours as well due to the drag save feature.

**Comment by eight04** [comment]
> Broken

Can you elaborate? Is there an error popped up? It will also help if you can post a screenshot.

**Comment by brazenvoid** [comment]
Sorry, I was testing v0.10.2 and it seems to work completely fine.

**Comment by brazenvoid** [comment]
An example of broken picker:
![Annotation 2019-08-16 102316](https://user-images.githubusercontent.com/8722533/63145245-17093580-c010-11e9-92c1-10ba6ab8ca92.png)

On:
https://mangakakalot.com/chapter/kakegurui/chapter_62

**Comment by brazenvoid** [comment]
An example of corrupt file downloaded from a website:
[079.zip](https://github.com/eight04/image-picka/files/3508166/079.zip)

**Comment by eight04** [comment]
It seems that the extension failed to fetch the image before displaying it. Since the single-download works fine, I guess the problem is related to indexedDB (images are stored in the database when the picker is opened).

I'd like to know if there is an error in two consoles.

*Console for picker*

1. Open the picker.
2. Press F12 to open the dev tools.
3. Click "Console" and take a screenshot.

*Console for background*

1. Open `about:debugging#/runtime/this-firefox`.
2. Find the extension, click `Inspect`.
3. Click `Console` and take a screenshot.

**Comment by brazenvoid** [comment]
The second console just leads me to the usual console. The usual console has one error per image:
```
Error: "undefined"
    load moz-extension://ac861aeb-041e-4db5-9362-a56fc0a54c8e/picker/picker.js:304
progress.js:16:17
    add moz-extension://ac861aeb-041e-4db5-9362-a56fc0a54c8e/picker/progress.js:16
```

**Comment by yfdyh000** [comment]
@eight04 https://github.com/eight04/image-picka/issues/202 seems to have disappeared, it contains a similar problems.

**Comment by eight04** [comment]
I forgot to mention that you have to close the preview tabs before opening the background page.

@yfdyh000 The link leads to 404. I even don't know that issues can be deleted on Github.

**Comment by brazenvoid** [comment]
![Annotation 2019-08-16 105811](https://user-images.githubusercontent.com/8722533/63146570-c6e0a200-c014-11e9-836d-8cfa0635015a.png)
I didn't mention but the page gives me this on access, I then click "Addons", then your addon, and then debug. There is no inspect option. Perhaps you are on the developer or nightly build?

**Comment by eight04** [comment]
Sorry for the wrong instruction, here is the correct one for FF<70:

1. Open `about:debugging`.
2. Check `Enabled add-on debugging`.
3. Find the extension, click `Debug`.

**Comment by brazenvoid** [comment]
![Annotation 2019-08-16 112722](https://user-images.githubusercontent.com/8722533/63147853-dcf06180-c018-11e9-84b0-a9bbe079dd66.png)
![Annotation 2019-08-16 112653](https://user-images.githubusercontent.com/8722533/63147855-dd88f800-c018-11e9-9ebf-a2ed011ec9fe.png)

**Comment by eight04** [comment]
Try to click the "Reset filter" button and check the "Persist logs" option. After that, restart the browser then:

1. Open the background debugger.
2. Open picker and confirm that images are not loaded.
3. Take screenshots of the background debugger.

Hope this can clean up some errors coming from other extensions.

**Comment by brazenvoid** [comment]
Sorry, am at the office now. My responses will be inconsistently delayed.

![Annotation 2019-08-16 152103](https://user-images.githubusercontent.com/8722533/63161467-98c18900-c039-11e9-80ad-299712c5d865.png)

**Comment by eight04** [comment]
It doesn't give us useful information. Try testing if an image can be correctly cached:

1. Open the background debugger.
2. Open `http://example.com` and make sure it is the only active tab (no multiple windows).
3. In the background debugger, run the following command:
    ```js
    imageCache.add({url: "http://placehold.it/50", tabId: (await browser.tabs.query({active: true}))[0].id})
    ```
    
It should report the information of the cached image.

**Comment by brazenvoid** [comment]
Error: Could not establish connection. Receiving end does not exist.

**Comment by antohin91** [comment]
![изображение](https://user-images.githubusercontent.com/54191297/63201962-e4f3e400-c0a0-11e9-84ce-fcf144b772f6.png)
![изображение](https://user-images.githubusercontent.com/54191297/63202009-2b494300-c0a1-11e9-8f4b-ad5c2ac1f60a.png)
there are more pictures to download from the page after the fact.
writes different values ​​of the number of downloaded images when clicking on the extension, although in fact there were no changes on the download page
![изображение](https://user-images.githubusercontent.com/54191297/63202119-b9252e00-c0a1-11e9-963b-d7fab35bebe9.png)
![изображение](https://user-images.githubusercontent.com/54191297/63202128-c04c3c00-c0a1-11e9-9e6c-25d51600205f.png)

![изображение](https://user-images.githubusercontent.com/54191297/63202158-dbb74700-c0a1-11e9-9d37-eae69d1beed8.png)
scroll up - already the value has changed to 902
something with caching from the page, the loaded pictures merges from memory

**Comment by antohin91** [comment]
I’ve increased the scale on the page, if you return it by 100%, it will show
![изображение](https://user-images.githubusercontent.com/54191297/63202372-c0990700-c0a2-11e9-8b03-763abb4333ec.png)
![изображение](https://user-images.githubusercontent.com/54191297/63202404-e58d7a00-c0a2-11e9-8c06-017c65281a75.png)

**Comment by eight04** [comment]
@antohin91 please open a new issue, the problem is different from this one.

**Comment by eight04** [comment]
> Error: Could not establish connection. Receiving end does not exist.

That's pretty weird. This error usually occurs when the background can't communicate with the tab. Are you sure that the active tab is `example.com`? Also, I'd like to know where the error occurs. Can you post a screenshot including the stack trace?

**Comment by brazenvoid** [comment]
All three relate to the Error "undefined"

![Annotation 2019-08-17 130715](https://user-images.githubusercontent.com/8722533/63208680-bef63000-c0f0-11e9-8834-8e03aa5644e9.png)

![Annotation 2019-08-17 130812](https://user-images.githubusercontent.com/8722533/63208681-c1f12080-c0f0-11e9-9f10-26832cae0c31.png)

![Annotation 2019-08-17 131134](https://user-images.githubusercontent.com/8722533/63208682-c61d3e00-c0f0-11e9-936b-cba42afa8a13.png)

**Comment by eight04** [comment]
It seems that pictures were correctly fetched (you can see the image type, size, etc), but failed to put them into indexedDB. Did you disable indexed DB in the setting?

**Comment by brazenvoid** [comment]
No, I don't even know there is a setting for it...

**Comment by eight04** [comment]
Does it work in a fresh profile? To create a new profile: https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

**Comment by brazenvoid** [comment]
Yes, it worked fine on a new profile

**Comment by eight04** [comment]
Then there must be a setting/extension which disables indexedDB. I suggest creating a new profile and configuring it as the old one, so you can check which option causes the issue. On the other hand, there may be some legacy settings inherited from old versions of Firefox. Creating a new profile will also reset them.

**Comment by brazenvoid** [comment]
I knew what you were going to say next. But frankly my profile is just too old, from the wee days of Firefox. I am perfectly settled in what I have configured for it and no longer remember most settings. Its like rebuilding the profile, line by line which I am not going to do. 

Thanks for the effort though. I guess I am going to stick with drag function from yours and picker function from Image Downloader or perhaps I can downgrade to 0.10.2, it works fine with my profile...
