### ISSUE TITLE
stopped parsing from such links // * [@ id = "archives"]

### ISSUE THREAD

**Issue by antohin91** [eight04/image-picka#206]
Hey. Previously, such links https://2020models.tumblr.com/archive downloaded normally, it is especially useful when pick image goes to internal links. Now the problem is when scrolling down the page, pick image finds a maximum of 110 photos, until I understand what it is based on, I noticed that when scaling it takes into account more images, although this did not happen before, literally a week ago it was not. I did not update anything at home.
![изображение](https://user-images.githubusercontent.com/54191297/63228944-2658d080-c214-11e9-9c0d-b8862a3c7fcb.png) scale 40%
![изображение](https://user-images.githubusercontent.com/54191297/63228954-4c7e7080-c214-11e9-9b56-fff06fca3b1d.png)
at scale 100%
![изображение](https://user-images.githubusercontent.com/54191297/63228964-64ee8b00-c214-11e9-9d33-1337358787e9.png)
same page - not updated, standard scale
![изображение](https://user-images.githubusercontent.com/54191297/63228973-82bbf000-c214-11e9-808d-277e88d93105.png)

**Comment by antohin91** [comment]
than in my opinion it was convenient, I went to the user's archive, scrolled for a year, downloaded everything, the website page used less thumbnails and resource, and downloaded the full size, which was very pleasing.

**Comment by eight04** [comment]
Maybe Tumblr unloads images outside of the screen. However, I'm not sure what do you want to achieve. If you want to scrap all posts from Tumblr, I think it will be faster/more efficient to use a scraping tool designed for Tumblr.

**Comment by antohin91** [comment]
Thanks, of course, maybe tumblr itself has defended itself, updated. Yes to me only in order to pull out pictures. sorry, not one extension does not take this page as with embedded links to enlarged images. other extensions take thumbnails from the page or don’t see pictures at all.

**Comment by eight04** [comment]
BTW, I can't visit the URL. I thought Tumblr blocked all NSFW content, no?
