### ISSUE TITLE
browser cache feature

### ISSUE THREAD

**Issue by yeappa** [eight04/image-picka#207]
**Try to download images from browser cache** feature was working in old versions. 
at v0.11.1 this feature is not working at all.

is there any possible solution to fix?
Thanks

**Comment by eight04** [comment]
Can you elaborate? Steps to reproduce?

**Comment by yeappa** [comment]
trying on some other addons for save from cache feature. i think its broken on my side.
may wait for my try outs?

**Comment by yeappa** [comment]
> 
> 
> Can you elaborate? Steps to reproduce?

Browser cache feature not working **browser-wide** (globally) when;
This Ad-blocker addon feautres are selected: 

- Disable Pre-fetching
- Disable hyperlink auditing
- Any cooki-dialog blocker filter lists
