### ISSUE TITLE
[Bug] filename must not contain illegal characters

### ISSUE THREAD

**Issue by RikisX** [eight04/image-picka#208]
Error saving images (Ctrl+click or drag), if filename contains "%E2%80%8F"
Error text: filename must not contain illegal characters
Image example with filename in question: https://www.a-rubi.co.il/wp-content/uploads/2014/06/%E2%80%8F%E2%80%8FZahalanovK.png

Windows 10. Firefox 69.0.2

**Comment by eight04** [comment]
https://www.fileformat.info/info/unicode/char/200f/index.htm

**Comment by RikisX** [comment]
I think filename (path excluded) should be sanitized with this:

```
function gConvertToSpaceRegExp ()  {
  // Note: we remove colons everywhere to avoid issues in subresource URL
  // parsing, as well as filename restrictions on some OSes (see bug 1562176).
  /* eslint-disable no-control-regex */
  switch (runtime.PlatformOs) {
    // On mobile devices, the file system may be very limited in what it
    // considers valid characters. To avoid errors, sanitize conservatively.
    case "android":
      return /[\x00-\x1f\x7f-\x9f:*?|"<>;,+=\[\]]+/g;
    case "win":
      return /[\x00-\x1f\x7f-\x9f:*?|]+/g;
    default:
      return /[\x00-\x1f\x7f-\x9f:]+/g;
  }
 
}

function sanitize(leafName) {
    if (runtime.PlatformOs == "win") {
      leafName = leafName
        .replace(/</g, "(")
        .replace(/>/g, ")")
        .replace(/"/g, "'");
    }
    return leafName
      .replace(/[\\/]+/g, "_")
      .replace(/[\u200e\u200f\u202a-\u202e]/g, "")
      .replace(gConvertToSpaceRegExp(), " ")
      .replace(/^[\s\u180e.]+|[\s\u180e.]+$/g, "");
  }
```

**Comment by eight04** [comment]
We already have an `escapeVariable` function:
https://github.com/eight04/image-picka/blob/29116aca07f4b92f8eebc21b374b184539276257/extension/background/background.js#L508

It might be better to decide a range (or use the [actual list](https://www.fileformat.info/info/unicode/category/Cf/list.htm)?) and check which character is invalid in downloads API. We have to test Firefox and Chrome, they have different behaviors.

**Comment by RikisX** [comment]
I have posted how Firefox validates for Webextension API.
At least this one is must for Firefox extension:

`.replace(/[\u200e\u200f\u202a-\u202e]/g, "")`

**Comment by eight04** [comment]
Can you post the link to the source?
