### ISSUE TITLE
Hover button appears at top of page out of the image in direct image view

### ISSUE THREAD

**Issue by jedikalimero** [eight04/image-picka#217]
When the URL is an image, so you are viewing that image on a black background, the hover button appears at the top of the page aligned horizontally with the left border of the image (in case you are using the default position of top left).
Because of this, you can't click on the hover button because it is outside of the image limits and when you move the pointer out of the image, the button disappears. Persistance can help giving the user some time to move from the image to the button but he/she has to be quick before the button disappears. Increasing the time is good for this situation but bad for other more regular situations.

There is an add-on called Double-click Image Downloader that suffered this same issue. The author recently managed to find the cause and solve it. It is a bug in Firefox, but he managed to overcome it and make the add-on work without needing to wait for the bug to be fixed. Here is the URL to the issue where he explains the cause and points to the buggy CSS command, so maybe it is of help for you too:
https://gitlab.com/Marnes/doubleclick-image-downloader/issues/50

**Comment by eight04** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1610734

**Comment by eight04** [comment]
Fixed in 0.12.1
