### ISSUE TITLE
(Help Wanted) Ambiguous Image Extension With Download From Thumbnail

### ISSUE THREAD

**Issue by Misdirected** [eight04/image-picka#218]
### Goal:
Batch-download images from thumbnail gallery when full-sized file extension can not be assumed to match thumbnail extension and cannot be determined from thumbnail-link.

### Context:
Thumbnail links lead to landing pages with non-helpful URLs (SQL index, assumedly); not directly to full-sized image. All thumbnails are .jpg, but full-sized images can be .jpg, .png, .gif, .bmp (and .flash, .webm / scope?; perhaps possible). I can currently have a regex set to determine the full-sized file by assuming the extension, at the cost of not fetching any other format.

### What I have so far:
```
# bat.com
foo\.bar\.com\/preview.+([\da-f]{32})\..\w+$
bat.bar.com/data/$1.png
```
But this just works for .png files, obviously.
My attempts to set up `"this"|"that"` have been uninformed thrashing-about in the options-page. Before I go any further, I thought I'd post here for guidance; please advise.

**Comment by eight04** [comment]
To achieve your goal, you need a tool which can:

1. Fetch the content of the thumbnail link.
2. Parse the content and find the URL of the full-size image/video.
3. Download the URL.

Some suggestions:

1. If you often have to download resources from this website, it might be better to find a specific tool which is designed for it.
2. If you only need pictures (no videos/flash), you can use another extension to open all thumbnail links to new tabs and fetch all images at once using the "Pick images from right tabs" command.
3. If you have JS knowledge, you can write a userscript to resolve it.
