### ISSUE TITLE
Double-Click to Save Image is Broken

### ISSUE THREAD

**Issue by StripedPuppy** [eight04/image-picka#221]
**Browser Version:** Firefox 68.4.2 ESR
**Operating System:** Windows 7 x64
**Problem:** Double left clicking an image doesn't automatically save it as setup in the options tab. Nothing happens.

**Comment by DenB10** [comment]
Hi,
I agree and by me, single click to download a single image doesn't work too. In fact, to download a single image, only drag and drop or download button are working.
Same browser version and same OS as StripedPuppy.

**Comment by oddPT** [comment]
Same problem. Started noticing it yesterday.
Have it set to single click download while pressing Ctrl.

Tried Drag and Drop and it worked. Pick images from tabs also working.

72.02 64bit
W10 x64

**Comment by eight04** [comment]
Should be fixed at 0.12.2
