### ISSUE TITLE
Customize image borders in Gallery

### ISSUE THREAD

**Issue by Bamajon1974** [eight04/image-picka#225]
Ability to customize border color and thickness, text color/style/type in gallery. Thanks!

**Comment by eight04** [comment]
I think we can add a "Custom CSS" option that allows users to customize the extension page through CSS.

**Comment by Bamajon1974** [comment]
That would be the best option. I am no coder but I can figure out a few
lines of CSS code to customize. You might want to add a sample CSS code to
help out non-coders like me.

Thanks, Jon

**Comment by Bamajon1974** [comment]
Thank you. When will the next version hit the Chrome/Firefox extension/add-on stores?

**Comment by eight04** [comment]
Now you can install v0.13.0 from AMO.

**Comment by Bamajon1974** [comment]
Thank you. Do you have a drop in installer for the Chrome version or do you still have to build it from scratch?

**Comment by eight04** [comment]
It is still not on Chrome store but there is a pre-built zip. Follow the instruction here:
https://github.com/eight04/image-picka#chrome

**Comment by Bamajon1974** [comment]
Got it. I managed to load the unpacked image successfully. Where (as in what directories) would you suggest storing the unpacked files? 

Also, there are two errors with the extension (Below with the highlighted code). What do they mean and can they be fixed? 

Unrecognized manifest key 'browser_specific_settings'.

 "browser_specific_settings": {
    "gecko": {
      "id": "image-picka@eight04.blogspot.com",
      "strict_min_version": "55.0"
    }
  },

found unexpected key 'browser_style'
  "manifest_version": 2,

**Comment by eight04** [comment]
> Where (as in what directories) would you suggest storing the unpacked files?

As a developer on Windows, I put my works under `D:\dev\`.

> Also, there are two errors with the extension (Below with the highlighted code). What do they mean and can they be fixed?

It means that Chrome doesn't recognize these settings. To fix it, you have to contribute to Chromium project. Though I guess this is a small problem that it will be labeled with low priority.

Note that these settings doesn't affect functionality. `"strict_min_version": "55.0"` means you need Firefox version >= 55.0 to use this extension.
