### ISSUE TITLE
Naming & saving of directly opened image

### ISSUE THREAD

**Issue by Fixer-007** [eight04/image-picka#226]
I love your addon! It is great, here is suggestion (Firefox 72 & Win):

Currently if you directly open an image itself in a browser tab for example this URL:
https://gamepedia.cursecdn.com/minecraft_gamepedia/thumb/a/a8/Alpha.png/1200px-Alpha.png
and then save it via Image Picka (via menues or hover button), it gets saved like this on my HDD:
```
\Pics\1200px-Alpha.png (Image PNG, 1200 х 635 pixels)\1200px-Alpha.png
```
This is according to default ```Pics/${pageTitle}/${name}${ext}``` saving scheme.
I suggest saving those directly opened images like this (by omitting pagetitle part): 
```
\Pics\1200px-Alpha.png
```

This will reduce the clutter with long named directories with just 1 file inside, instead it will go to root of Pics. Thoughts?

**Comment by eight04** [comment]
What is your browser?

**Comment by eight04** [comment]
This can be achieved with an option: `Use an empty title for a standalone image`.

Or, should we add a `Filename pattern for standalone image`?

**Comment by Fixer-007** [comment]
```Filename pattern for standalone image``` with Pics/${name}${ext} set to default I guess will be a nice way.

**Comment by Fixer-007** [comment]
Thanks, seems fine for me.
