### ISSUE TITLE
"SERVER_FORBIDDEN" on Pixiv

### ISSUE THREAD

**Issue by aprunai** [eight04/image-picka#231]
Firefox 75.0 (64bit) on Linux Mint 19.1. When clicking Image-picka button over a picture on Pixiv (www.pixiv.net), the download fails with the message "SERVER_FORBIDDEN".
The extension works regularly on other sites.

**Comment by eight04** [comment]
Try enabling the "Download from cache" option.

**Comment by aprunai** [comment]
Thank you, this solved the problem!

By the way, ImagePicka is superb! Love this extension!
Keep up the good work!
