### ISSUE TITLE
Add pageName from URL

### ISSUE THREAD

**Issue by cbadoud** [eight04/image-picka#232]
In batch download, it should be very useful if there is a pageName coming from the URL, e.g. http://www.example.com/folder1/folder2/pageName?view=param
I've tried to put this code in text box, but it didn't work:
`${new RegExp("/(\w+)(\.\w+)+(?!.*(\w+)(\.\w+)+","gi").exec(String(pageUrl))}`

**Comment by eight04** [comment]
Do you mean something like image filename but based on `pageUrl`?
https://github.com/eight04/image-picka/blob/10ac32b12af2c90e38ab78b09247f9a2f11d2e42/src/background.js#L587

**Comment by cbadoud** [comment]
I've tried a Regex replace one pageUrl, but it didn't work, that's why I would like a new variable called `pageName`

**Comment by eight04** [comment]
Should we also add `pageExt`?

**Comment by cbadoud** [comment]
I don't think it's useful; my idea is to download product images from e-shop, and I usually do this when taking the "page name" and adding numbers to it.

**Comment by eight04** [comment]
So the `pageName` will also include the extension part if is has an extension? For example:

* pageUrl - `http://www.example.com/folder1/folder2/my-page.html?view=param`
* pageName - `my-page.html`

**Comment by cbadoud** [comment]
No, it shouldn't include extension, because extension will come from the pictures!

**Comment by eight04** [comment]
What if the page name is empty e.g. `http://www.example.com/folder1/folder2/?view=param`

**Comment by cbadoud** [comment]
In this case, we should consider "folder2" as the pageName
