### ISSUE TITLE
Drag and drop saves invisible images

### ISSUE THREAD

**Issue by RikisX** [eight04/image-picka#233]
When you drag and drop link and it has 2 images and first image is not visible it will save hidden image. There is no reason to save invisible images. Can you please ignore them.

Example:
```
<a href="https://example.com">
<img src="imageThumbnail.jpg" style="display: none;" >
<img src="imageFullSize.png" >
</a>
```

**Comment by eight04** [comment]
https://github.com/eight04/image-picka/blob/10ac32b12af2c90e38ab78b09247f9a2f11d2e42/src/lib/dragndrop.js#L135-L138

**Comment by RikisX** [comment]
Maybe it should be something like that:
```
var img = e.target; 
if (img.nodeName == "A") { 
      var imgs = img.querySelectorAll("img"); 
      for (var i = 0; i < imgs.length; i++) {
       img = imgs[i];
       if (window.getComputedStyle(img).display !== 'none'){
         break;   
       }
     }
} 
```
