### ISSUE TITLE
Take real image thumbnail back

### ISSUE THREAD

**Issue by eight04** [eight04/image-picka#237]
https://addons.mozilla.org/en-US/firefox/addon/image-picka/reviews/1570634/

**Comment by tonglil** [comment]
I think I am experiencing the same issue.
0.13 no longer shows thumbnails in the selection view, only empty boxes.
I reverted to 0.12.3 from the addon page and it works correctly again https://addons.mozilla.org/en-US/firefox/addon/image-picka/versions/

**Comment by eight04** [comment]
Are you using the addon in private windows? It might be the same issue as #240

**Comment by tonglil** [comment]
It was in regular windows, not private/incognito.
Will try 0.13.1.
