### ISSUE TITLE
Blob URL images are broken in private windows

### ISSUE THREAD

**Issue by Esoppant** [eight04/image-picka#240]
For about 10 days (either after the last add-on update, or the last Firefox update) the thumbnails in the image picker screen are invisible in private Firefox windows. They still download fine, have a blue outline, and are selectable and deselectable; but there are no images visible.

**Comment by eight04** [comment]
https://github.com/eight04/webextension-test/tree/blob-image
Can't reproduce in Nightly 96.0a1.
