### ISSUE TITLE
The configuration is deleted when I use CCleaner. Why?

### ISSUE THREAD

**Issue by Juan498** [eight04/image-picka#241]
I would like to know why the configuration is deleted after using CCleaner. Thank you!
Using Mozilla Firefox v79.0 (64 bit)

**Comment by eight04** [comment]
I think you have to ask the developer of CCleaner. I have no idea how they "clean" the browser extension.

**Comment by brazenvoid** [comment]
It is a known issue and many plugin authors plainly state this.

**Comment by eight04** [comment]
I got an email from Mehdi.Alimadadi who was also hit by this bug. It seems that this is caused by outdated CCleaner:

> 
> Since you mentioned "the addon uses Firefox sync", that was a hint for me to further investigate this issue and I found these links:
> 
> - "CCleaner is now deleting synched Firefox extension data" at (https://mspoweruser.com/ccleaner-is-now-deleting-synched-firefox-extension-data/)
> - "CCleaner is deleting Firefox extension settings in Firefox 79" at (https://support.mozilla.org/en-US/kb/ccleaner-deleting-firefox-extension-settings-firef)
> 
> So, basically there are two files, Storage-sync-v2.sqlite-shm and storage-sync-v2.sqlite-wal, that are the culprit. Either exclude them from cleaning or use the latest CCleaner version, which unfortunately is some sort of adware.
