### ISSUE TITLE
ver 0.13.1 Filenaming is broken - Chrome

### ISSUE THREAD

**Issue by StrannikD** [eight04/image-picka#242]
Hi! 
the filename of a saved pics files looks like "56833935-156b-4d8c-a00f-19599c6513d3"

It's just the same problem, as was with another addon SingleFilez, I found the solution:
chrome-extension://offkdfbbigofcgdokjemgjpdockaafjg/extension/ui/pages/help.html
disable the option "Misc. > Save pages in background".

but there is no such option for "image-picka". 

Chrome 86.0.4240.75

**Comment by eight04** [comment]
Which browser? How did you save the image? It sounds like you were downloading the image from blob URLs manually.

**Comment by eight04** [comment]
Do you use some kinds of download manager plugin on Chrome/Vivaldi? It sounds like there is a plugin that renames downloaded files automatically according to the URL.

**Comment by StrannikD** [comment]
Oh, yes! I found the source of this DownThemAll!
https://chrome.google.com/webstore/detail/downthemall/nljkibfhlpcnanjgbnlnbjecgicbjkge
with disabled DownThemAll filenames are saving according to mask.
Thank you very much!
