### ISSUE TITLE
Image picka may save image with incorrect extension

### ISSUE THREAD

**Issue by Fixer-007** [eight04/image-picka#243]
Yes, it is related to webp as usual, for example: https://res.cloudinary.com/lmn/image/upload/e_sharpen:100/f_auto,fl_lossy,q_auto/v1/gameskinnyc/l/a/s/last-guardian-banner-15jun15-q76w-91802.jpg

Try saving it via Image Picka you will get incorrect filename.webp.jpg extension, firefox on its own saves it properly as .webp.

It seems different in different cases, in those examples below it saves differently then firefox itself (not sure if that's a problem):
https://vignette.wikia.nocookie.net/cardfight/images/9/9b/BT08-074EN-C.jpg (served as webp) - firefox saves it correctly as webp, but imagepicka actually requests it as jpg with correct .jpg extension.
https://vignette.wikia.nocookie.net/nox/images/1/1a/WizardClass.png (served as webp) -  firefox saves it correctly as webp, but image picka actually requests it as png with correct .png extension.

Firefox 81 / Image Picka 0.13.1

**Comment by eight04** [comment]
I can't reproduce on Firefox 83. Did you download the image from a specific page?

**Comment by Fixer-007** [comment]
I think I've used "gallery saving feature" on each separate image

**Comment by eight04** [comment]
Maybe I misunderstood the issue. Do you expect the extension to save `https://vignette.wikia.nocookie.net/cardfight/images/9/9b/BT08-074EN-C.jpg` into `BT08-074EN-C.webp` instead of `BT08-074EN-C.jpg`?

**Comment by Fixer-007** [comment]
Open this:
https://res.cloudinary.com/lmn/image/upload/e_sharpen:100/f_auto,fl_lossy,q_auto/v1/gameskinnyc/l/a/s/last-guardian-banner-15jun15-q76w-91802.jpg
click on image picka blue arrow, notice how it is saved as last-guardian-banner-15jun15-q76w-91802.webp.jpg (incorrect extension)

**Comment by eight04** [comment]
I can't reproduce on Firefox 81 + Windows  10.
![image](https://user-images.githubusercontent.com/1324510/97522055-d8278b80-19d9-11eb-9bb9-51b7e3bcb020.png)

What is your OS?

**Comment by Fixer-007** [comment]
Windows 7

**Comment by eight04** [comment]
https://github.com/eight04/image-picka/blob/d548834ee6503c6a207e8985372fddbbc9eca133/src/background.js#L574
It seems that image picka doesn't treat webp as an image.
