### ISSUE TITLE
Add a button to retry when there is an error in batch download

### ISSUE THREAD

**Issue by elvisef** [eight04/image-picka#245]
I came up with a problem of downloading files, where the server says: no.

Imagine a page, with about 120 pictures (every picture has about 4000x6000pix of its size, but on the page pictures are smaller, not forced so big).

ImagePicka addon reads every picture, one by one, but... some pictures are not being read.
In these places I see a red square.

But.. when I enter F5 on my keyboard, it "re-reads" all images (I suupose it uses cache, the browser or ImagePicka?) and some new images are on the list visible.

I suppose the source server (in my case it was "imgadult") blocks too many connections at a certain amount of time.
Am I right ?

It would be great to have an option to set a "time delay" or something, to be aware that pictures should not be read so fast.
Or have some kind of button, to "refresh" images, but only these which were not read (red squares).

Is it possible ?
Anyway, do You have any other suggestions to this problem/issue ?

**Comment by eight04** [comment]
On each tab, Image Picka fetches 5 images at the same time. The browser itself also restricts the number of connections to the same server (default: 6).

I think you might hit the server's bandwidth limit. You can [open browser toolbox](https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox), click "Network" panel, so you can see the loading process when picking images.

**Comment by elvisef** [comment]
Thanks for information. I will try this next time.
Would be nice to have such button of course. 
But also would be nice to have such option to change the default "5" ImagePicka connections at the same time (here the max of 5 can be restricted, no problem, but with option to enter other number, smaller than 5).

**Comment by eight04** [comment]
Closing since we have an option to retry automatically now.
