### ISSUE TITLE
More galleries = reading getting slower and slower

### ISSUE THREAD

**Issue by elvisef** [eight04/image-picka#246]
Hello.

I have a technical question. Let's say I am doing such thing:

1.Open URL with a gallery
2.Use ImagePicka t oread contents (I mean images)
3.Save & close tab

And I am doing this hmm.... 40 times ?
So Open URLs, one by one, read images and save and close.
And the more galleries I open (independently, not in the same time), more slowly images are getting read.

I don't know if You understand what I mean.
I tried to fix it by clearing Firefox cache, offline data, whatever, and restart FF - no real effect I think.
Many times my Firefox died, and I lost everything, because before it crashed, I cleared every cache.

What kind of cache I need to clear, to make ImaePicka work fast again ?

These images under URL tabs I open, are about 2000 to 5000 pixels (I am using MaxUrl addon to show direct links on pages).
But if I clean the FF cache, these images read by MaxURL should be removed, right ? Because it is just a browser cache.

Can someone advise me, what I need to do ?

**Comment by eight04** [comment]
1. Why do you think that it relates to browser cache? The memory goes up each time you pick images and never goes down?

2. Could you inspect the image in the picker (right-click > inspect element) and see whether the image is loaded from blob URL? If it is, you should see something like `style="background-image: url(blob:...)"` in the img tag.

3. Does it happens to all sites or this site only? Could you post the URL?

4. > restart FF - no real effect

    Do you mean the site is still slow after restarting the browser? How about disabling the extension before restarting the browser?

**Comment by elvisef** [comment]
Hello. Sorry for the delay...

Am I able to paste a "nsfw" link here ?
I will paste a sample but within a screenshot.

![firefox_2021-04-29_07-49-02](https://user-images.githubusercontent.com/25976749/116507339-5dbfc180-a8bf-11eb-8b33-76165b67d6a8.png)

Such image is about 5000x7000px (approximately). And on the source page there are for instance 25 images (+5 pagination pages, but I've used only first one).

![firefox_2021-04-29_07-54-40](https://user-images.githubusercontent.com/25976749/116507671-0bcb6b80-a8c0-11eb-9d40-0169c5c167f2.png)
![firefox_2021-04-29_07-57-02](https://user-images.githubusercontent.com/25976749/116507820-54832480-a8c0-11eb-829b-af521927ca27.png)
