### ISSUE TITLE
[question] Example of use filename patterns

### ISSUE THREAD

**Issue by elvisef** [eight04/image-picka#247]
Hello.

Will You give me a pattern example basing on a sample filename I've prepared ?

My current pattern is:
`__imagepicka/[${pageHostname}] ${pageTitle} [${dateString}]/${index} - ${name}${ext}`

Sample page title would be:
`This is a site with Rubik cubes - index001 - something else`

I would like to have only this as a title (just cut the first sentence only, until first '-' character):
`This is a site with Rubik cubes`

Is it possible ? How to write it ? Can I use regular expressions here (parenthesies) ?

**Comment by eight04** [comment]
Currently regexp is not supported. See #64. For this case, you may use `.split(' - ')` and get the first item.

**Comment by elvisef** [comment]
Thanks for info.
I've spent some time on trying my best in one line, but finally I did it.

One example of how I used it:
`Image Picka/[${hostname}]/${pageTitle} [${pageUrl.slice(pageUrl.replace(/\/$/,'').lastIndexOf('/')+1,pageUrl.length-1)}]/${name}${ext}`

..and it works pretty nice.

Thanks!
