### ISSUE TITLE
[question] Date format change

### ISSUE THREAD

**Issue by elvisef** [eight04/image-picka#248]
Hello.

Based on this info: `dateString: a date string in format year-month-day hour minute second e.g. 2018-01-18 08 28 56.`

How to change this:
`2018-01-18 08 28 56`

to this:
`2018-01-18`

?

One more question. How to use the "Date" object mentioned here: `date: an instance of JavaScript Date.` ? 
At least one example please, ho wto use it with filename pattern.

**Comment by eight04** [comment]
You can split the string by space and take the first element.

For `Date` object, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date. For example, `date.getTime()` to get the timestamp.

**Comment by elvisef** [comment]
Thanks.
