### ISSUE TITLE
[question] How to cut out 'www' from 'pageUrl' pattern ?

### ISSUE THREAD

**Issue by elvisef** [eight04/image-picka#249]
Hello.

Based on this: `pageUrl: URL of the page.` I'd like to cut the "www" from the string.

Example:
a hosting is `www.somethingweird.net`
and after change would be `somethingweird.net`

Because some hosting names are too long, (even without 'www' part).

How to do this, using these "eval" expressions, can You give me an example plase ?

**Comment by eight04** [comment]
`pageUrl` is the full URL including protocol and path. If you just want the host name, you can try `pageHostname.slice("www.").join("")`

**Comment by elvisef** [comment]
What about something like this - using regex ?
`Image Picka/[${hostname}]/[${pageTitle}] pageUrl.match(/https:\/\/www\..+\/(.*)\//)[1]/${name}${ext}`

This code does not work. Can You tell me, what is wrong here ?
Can I use any regex in this way ?
