### ISSUE TITLE
"Failed to load" error when trying to download an image from pixiv.net

### ISSUE THREAD

**Issue by Izenmir** [eight04/image-picka#251]
Hello! Since recently i get a "failed to load" error when trying to download an image from pixiv.net by ctrl+clicking. Firefox 85.0.2 
Everything works fine on other websites.

**Comment by eight04** [comment]
Hmm it seems that we can't get the cache anymore:
https://github.com/eight04/webext-hit-the-cache

In this case, I think we have to specify `referrer` header correctly.

**Comment by eight04** [comment]
According to this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1691907

You can get the old caching behavior by changing `privacy.partition.network_state` to `false` in `about:config`.

**Comment by Izenmir** [comment]
Thank you so much for the reply! Changing that privacy setting does indeed solve the issue. I guess i will be turning it off whenever i need to download something from pixiv. 
Also, thank you for this extension, it's great! I could not find any other extension with that simple ctrl+click save feature. And sorting to different folders is great too!
