### ISSUE TITLE
Check if folder name exists - create a new folder with a different name

### ISSUE THREAD

**Issue by elvisef** [eight04/image-picka#259]
Let's say I have a URL where every link have the same pageTitle. For example: "TEST".
And when I am downloading images (from these let's say 10 sub-urls), all files are in ONE folder.

I would like to have an index number, to each folder.

But is there a way to check if a folder exists, and if YES, just create a new one with the same name + index (or any other text, number, whatever) ?

**Comment by eight04** [comment]
> But is there a way to check if a folder exists, and if YES, just create a new one with the same name + index (or any other text, number, whatever) ?

Nope. Extensions have no access to the file system.

**Comment by eight04** [comment]
However, if you batch download these images, you can change the filename pattern to something like
```
${pageTitle} ${index}/${name}${ext}
```
so those images will be put in different folders.
