### ISSUE TITLE
file name mustnot be an absolute path

### ISSUE THREAD

**Issue by d3graph** [eight04/image-picka#261]
i have installed it on fresh installation on firefox developer edition 
on save it show this message file name must not be an absolute path 
following pattern is showing in box
C:/Users/mypc/Downloads/graphics/${pageTitle}/${index} - ${name}${ext}

**Comment by eight04** [comment]
You have to use a relative path for the filename. It is always related to the default download folder. Try changing the pattern to `graphics/${pageTitle}/${index} - ${name}${ext}`
