### ISSUE TITLE
キャッシュの読み込み速度

### ISSUE THREAD

**Issue by tenjouina** [eight04/image-picka#263]
一部のサイトではキャッシュの読み込み速度が速すぎると弾く設定をしているみたい
遅くするか設定出来るようにしてほしい
ttps://i9i9.to/c/1749984
こういう系のサイトは特に設定をちょくちょく変える

**Comment by eight04** [comment]
Would #245 i.e. adding a retry button solve your issue?

**Comment by tenjouina** [comment]
30以下の少数なら2.3回再読み込み（Ｆ5）で全部読み込みますが、それ以上だと１度弾かれると数分待たないとＦ5押しても1つも赤色を読み込まない

**Comment by eight04** [comment]
I can't access i9i9.to. Does it block Taiwan IP?

**Comment by tenjouina** [comment]
台湾ＩＰに変えてアクセスしてみましたがこちらも弾かれました
おそらく国単位でサイトのサーバー会社がブロックしているんだと思います
