### ISSUE TITLE
Zero-padding isn't working

### ISSUE THREAD

**Issue by gendalv** [eight04/image-picka#264]
windows 10, firefox 89.0.2
using the same string from help:  Image Picka/${pageTitle}/${String(index).padStart(3,"0")} - ${name}${ext}
just creates a bunch of files starting with
undefined -

**Comment by KrisadaFantasy** [comment]
Can confirm. Windows 10, Microsoft Edge Dev Version 93.0.957.0 (64-bit). Got **undefined** for supposed to be padding zeroes too.

**Comment by eight04** [comment]
Have you turned on the advanced option `Use simple expression in the filename pattern`?

**Comment by KrisadaFantasy** [comment]
> Have you turned on the advanced option `Use simple expression in the filename pattern`?

Working now, thank you and sorry for trouble!

**Comment by eight04** [comment]
Maybe we should just always use the expression and remove that option 🤔

**Comment by KrisadaFantasy** [comment]
Yes, turn it on now. I thought I have it on but maybe during the tinkering in Edge after migrating from Firefox I might accidentally disable it. I do agree that it should be remove as redundant!

**Comment by gendalv** [comment]
no clue what that option does, but it works now, thnks.
