### ISSUE TITLE
Something wrong happens - not all images are being saved

### ISSUE THREAD

**Issue by elvisef** [eight04/image-picka#268]
Images are 2832 x 4256 px.
[Sample original picture](https://cashmere-cuties.com/wp-content/uploads/2021/03/DSC_1189.jpg)

While reading pictures... immediately red squares appeared. What does it mean ?
The server is not blocking, because I can still see each picture in separate tabs.

![firefox_2021-08-24_00-28-37](https://user-images.githubusercontent.com/25976749/130527636-65ef6508-3a19-4479-a330-888eec4acde9.png)

If You need a full link, here it is (it can be a bit **NSFW** but it's still safe): [full link](https://www.fusker.xxx/en/?lid=2893766&offset=20340&special=preview)

Then the plugin crashes. No pictures can be downloaded/read in any other tabs, even after a browser restart. I tried even to purge cache and every history elements like browser information and so on.. nothing happens.
Only reinstallation of plugin worked.

Are these pictures too large ?

My Firefox version is: **91.0.1 (32 bit)** (windows 7)

**Comment by eight04** [comment]
Can't reproduce with Nightly 64-bit 93.0a1 20210904215148 + Image Picka 0.14.0.

Can you open the console (by pressing F12) and take a screenshot when the error occurs?

**Comment by elvisef** [comment]
I tried it just a minute ago, and this did not happen again.
But if I notice something, I will post it here.

I checked this on my laptop now, but this happened on my PC, so I will re-check this soon and let You know.
