### ISSUE TITLE
issue with saving images !!

### ISSUE THREAD

**Issue by on1no** [eight04/image-picka#269]
Hi And Sorry For My Bad English.
Please help.. i used Download with drag-n-drop and i save many images with no issue.. but some time I'm getting an error message !! and i don't know why?
And Please watch the video below..Is it possible to solve this issue!! and Thank you
https://user-images.githubusercontent.com/35997957/134283832-84ec7193-fa25-4d63-9388-526bcd3cdf5e.mp4

**Comment by eight04** [comment]
I can't reproduce with Edge Dev 97.0.1060.2/Image Picka 0.14.0.

What is your browser/extension version?
