### ISSUE TITLE
[SOLVED] Batch encode stopped working

### ISSUE THREAD

**Issue by J4V13R-B** [eight04/image-picka#27]
I began recently using this extension as a replacement of another one after the new Firefox Quantum upgrade and I was amazed by its good work. However, this morning the batch download feature stopped working. There is no failure message nor weird prompt, it only takes you out when you push the "save" button on the batch download dialog but nothing happens, no image is downloaded and, if the destination directory doesn't exist, it remains like this. I can still use the extension to download a single picture with the 'one click' feature perfectly.
I'm running it over ubuntu.
Is there someone else having the same issue? Any help?
Thank you.

**Comment by eight04** [comment]
Which version of Firefox are you using? I can't reproduce it on Windows 7 + Firefox 58.0b10 + Image Picka 0.5.1.

**Comment by J4V13R-B** [comment]
Image Picka 0.5.1 and Firefox 57.0.1 (64-bit) over Ubuntu 17.10.

**Comment by eight04** [comment]
Can't reproduce on Windows 7 + Firefox 57.0.1.

> if the destination directory doesn't exist, it remains like this

Does it mean that it only happens when the destination folder doesn't exist?

> I can still use the extension to download a single picture with the 'one click' feature

If you remove the destination folder of one-click downloaded images (or point it to a non-existent path), would that fail too?

Also, could you see if there is any error in the debugger when the download fails? [Tutorial](https://www.youtube.com/watch?v=HMozipAjrYA).

**Comment by J4V13R-B** [comment]
So, maybe the problem is about the platform.

It happens even if the folder doesn't exist. I've tried creating the folder manually but the issue persists (no image is downloaded to the existing folder either).

When I use the one-click feature I'm always prompted to define the folder so it works no matters if the folder exists or not.

I'll take a look at the tutorial and what the debugger shows. I let you know when I find out some new info.

**Comment by J4V13R-B** [comment]
Thanks for your help. I get to solve the problem. The debugging tool was so clear:

> [Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 505"  data: no]  (unknown)
> Error: filename must not be an absolute path

 I was using an absolute path to locate the images in the batch download filename pattern box and it seems that it only accepts relative ones. It would be great if the extension let you change the download directory and/or use an absolute path but it's not a big deal downloading the images to the Download folder and then moving them to the right place.

Thanks a lot for your help and for this great tool ;)

**Comment by eight04** [comment]
👍 

However the error should be displayed to users #30
