### ISSUE TITLE
Add blacklist and/or minimum image dimensions for batch download

### ISSUE THREAD

**Issue by xzorby** [eight04/image-picka#271]
Awesome extension! I use it mostly for batch downloading gallery images from a website that does user agent checks, so I have to open a new tab for each single image. Unfortunately, the single image pages are filled with dozens to hundreds of user icons (e.g. 50x50, 150x150 and 300x300 pixel images). This means that for a gallery of 30 images, I open the 30 tabs, and Image Picka (batch) loads some 5000 images. This makes the extension very slow.

I can use uBlock Origin to blacklist the icon domains, and that way Image Picka can't load the images in the batch pick images page. This speeds it up a little and saves some memory. However, the pick images page is still cluttered with all the not-loaded icons. Example sfw gallery [here](https://fetlife.com/users/4329473/pictures) (note: nsfw website that requires signing up). Here's a screenshot of the batch pick images page using 16 image tabs from that gallery: https://i.imgur.com/Z5mvg4L.png - 2859 (icons) out of 2875 images are blocked by uBlock Origin as intended, and the 16 larger images are visible, but manually picking which of those I want to save is annoying because of all the clutter.

Is there a way to blacklist domains and/or set minimum image dimensions, so these icons don't show up in the batch pick images page at all?

**Comment by eight04** [comment]
> set minimum image dimensions, so these icons don't show up in the batch pick images page at all

The main issue is that Image Picka doesn't know the size of the image until loading it. When you block the domain (using uBlock Origin), Image Picka still tries to load those icon (though all requests fail).

I think you can achieve a similar effect by adding a URL transform:
```
^http://domain\.to\.useless\.icon/.*
about:blank
```
This should be faster since it doesn't make the request at all. You can also hide those red squares with custom CSS:
```css
label[title="about:blank"] {
  display: none;
}
```

**Comment by eight04** [comment]
Disabling cache partitioning may also help: #270

**Comment by eight04** [comment]
BTW nice dark theme 👍

**Comment by xzorby** [comment]
Thanks, the URL transform worked perfectly!

**Comment by xzorby** [comment]
Is it possible to remove the isolate-tabs-border from the pick image page using CSS too? I'd like to keep the option for file naming, but I'd rather have the images together in a gallery instead of below of each other.
