### ISSUE TITLE
wait

### ISSUE THREAD

**Issue by tenjouina** [eight04/image-picka#272]
アクセス速度が速すぎて503エラーが起きます
1個取得ごとにwaitを付けることはできませんか？
赤色エラーはおそらくこれで解決します

**Comment by eight04** [comment]
Is this the same issue of #263?

Maybe we can add a new setting "Retry on failure", which allows you define max retry number and retry delay for a specific URL. For example:
```
<regex_matching_url>
<max_retries> <retry_delay> <exponential_backoff>
```
In your case:
```
^https://t\.i9i9\.to/.*
10 5 1.2
```

**Comment by tenjouina** [comment]
どこから追加出来ますか？
上のimportsettingに
<regex_matching_url>
<max_retries> <retry_delay> <exponential_backoff>
をコピーしても追加されない

**Comment by eight04** [comment]
I mean it will be a new feature in the next version of Image Picka.

**Comment by tenjouina** [comment]
なるほど、次のアップデート期待してます
