### ISSUE TITLE
Missing JPE extension while trying to get images from the server

### ISSUE THREAD

**Issue by elvisef** [eight04/image-picka#278]
Why ImagePicka does not allow to choose extensions that are allowed ?

Would be nice to have JPE format accepted here as well.
I have some images I need to get, and there is no way to do this.

**Comment by eight04** [comment]
Currently, Image Picka detects image URL with [image-extensions](https://www.npmjs.com/package/image-extensions). See also: https://github.com/arthurvr/image-extensions/issues/37

I think it is not really useful to make the list configurable (it's a 123 lines list). Maybe we should just insert missing extensions to the list in Image Picka.

**Comment by eight04** [comment]
Maybe we should build our own list according to https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types
