### ISSUE TITLE
Bypass hotlinked images

### ISSUE THREAD

**Issue by elvisef** [eight04/image-picka#279]
Hello.

How to bypass hotlinked, i.e. protected from viewing images, to download them succesfully by "ImagePicka" ?

**Comment by eight04** [comment]
Do you have an example?

**Comment by elvisef** [comment]
Yes, but be aware the forum is nsfw a bit. Just a bit.
The link: [https://forums.sexyandfunny.com/showpost.php?p=3033614&postcount=13241](url)
![firefox_CKLhuFk0M6](https://user-images.githubusercontent.com/25976749/151879086-bce73f02-c6b5-4534-b645-12cdeab9314a.png)
![firefox_r7iWXh2Qeb](https://user-images.githubusercontent.com/25976749/151879099-51ad2d8f-d298-4992-84b2-b4fe40542c02.jpg)

The thing is, while I'm on that page, I use a MaxURL FF extension to "update"/load images to their natural/bigger versions (if available of course).

As some services block images by hotlinking blockingm now if I use ImagePicka to get all big images, I only see "hotlinking error" from ImageTwist hosting. As below.

![firefox_Zi1DPYFoeG](https://user-images.githubusercontent.com/25976749/151879425-67e32f78-b3d5-49a6-8565-47ecb696ffde.png)

I just want to download images from other services, that are thumbnails as default when You enter that page.
How to bypass it using ImagePicka ?

**Comment by eight04** [comment]
Try disabling cache partitioning: https://github.com/eight04/image-picka/issues/270
