### ISSUE TITLE
[Feature request] Switch to the tab

### ISSUE THREAD

**Issue by yfdyh000** [eight04/image-picka#287]
Just an idea. When multiple tabs are open and multiple tabs are fetched at once, allowing switching to the original tab might help the user identify something.

**Comment by eight04** [comment]
Can you elaborate? When should the extension activate the original tab? Which tab is the original tabs when images are fetched from multiple tabs?

**Comment by yfdyh000** [comment]
> Can you elaborate? When should the extension activate the original tab? Which tab is the original tabs when images are fetched from multiple tabs?

Like a link. It may also provide things like page titles and url on tooltip.
A corner small icon or disabled in groups mode.
This idea is due to favicon-only when tabs crowded, as well issue #289.

**Comment by eight04** [comment]
> A corner small icon or disabled in groups mode.

What is groups mode?

**Comment by yfdyh000** [comment]
> > A corner small icon or disabled in groups mode.
> 
> What is groups mode?

Isolate Tabs, they render group boxes for now, which are more direct in my mind.

If #289 is resolved in Chromium browsers, the issues will be trivial, and I've thought more whimsical like title and close button on picka page, which is complicated.
