### ISSUE TITLE
[Feature request] [option] Opens the picka tab next to the original tab

### ISSUE THREAD

**Issue by yfdyh000** [eight04/image-picka#289]
It's an idea for the need to frequently probe the original page and opened the picka tabs in bulk (e.g. for preloading).
#287 is a workaround but difficult to return.
It may conflict with some extensions that act like this. However, implementing this option is easy.

**Comment by eight04** [comment]
What is your browser? We already use `openerTabId` so the browser should be able to sort the picker tab naturally.
https://github.com/eight04/image-picka/blob/d4807aee74ae59b48533f6aed951e4c5a3278cf3/src/background.js#L445-L448

**Comment by yfdyh000** [comment]
Google Chrome 98.0.4758.102 & MS Edge 99.

**Comment by eight04** [comment]
Seems that `openerTabId` is useless on Chrome: https://crbug.com/1298154

**Comment by yfdyh000** [comment]
> Seems that `openerTabId` is useless on Chrome: https://crbug.com/1298154

So, the "Open Tabs Next to Current" extension may be needed to mitigate this issue.
Feel free to close the issue or adding a workaround (like `tabs.move`).
