### ISSUE TITLE
[UI] Identify loading status on the save button

### ISSUE THREAD

**Issue by yfdyh000** [eight04/image-picka#291]
The current progress on the top of the screen, and when loading has been completed there will be no identifier.

A style of the save button in the lower right corner, will help the user to stay view. A color or borders, and even a reminder to confirm (like #288).

**Comment by yfdyh000** [comment]
Suppose that the loading takes 5 seconds, the user has to pay attention to the top and go back to the Save button after seeing the progress bar disappear. False start will lead to a failure of incomplete saves. So, a state change in the save button will save effort.
Incidentally, might it be better if the progress bar provides tooltips for the numbers? Although usually it doesn't last long, but when a failure occurs, the numbers might help?

**Comment by eight04** [comment]
> So, a state change in the save button will save effort.

Can you elaborate? What is the difference between progress bar and numbers on the save button? What makes the button better?

> False start will lead to a failure of incomplete saves

How about adding a confirmation to the save button when some images are still loading?



> might it be better if the progress bar provides tooltips for the numbers?

👍 We can add a tooltip like `${percentage} (${loaded} / ${total}), failed: ${failure}`

**Comment by yfdyh000** [comment]
> > So, a state change in the save button will save effort.
> 
> Can you elaborate? What is the difference between progress bar and numbers on the save button? What makes the button better?

A color/border instead of a number comparison? plus #284.

> 
> > False start will lead to a failure of incomplete saves
> 
> How about adding a confirmation to the save button when some images are still loading?

`if(loading) {confirm("")}`

> 
> > might it be better if the progress bar provides tooltips for the numbers?
> 
> 👍 We can add a tooltip like `${percentage} (${loaded} / ${total}), failed: ${failure}`

Good.
