### ISSUE TITLE
[idea] Option / button for erase downloads history

### ISSUE THREAD

**Issue by yfdyh000** [eight04/image-picka#292]
An idea. An option for when file download complete / Batch complete / ..., erase the completed downloads history.
They can take up a lot of space when saving a large number of pictures, affecting access to regular history, and causing loads to sync, viewer, database, etc.

Downloading files without history might be better, but it's not easy to work without native application.

p.s. Zipfile mode may be a workaround.
p.s. There may be some extensions that can do something similar.

**Comment by eight04** [comment]
👍 

I think we can have an option "Erase download history" which has three modes:

1. Never.
2. Erase all.
3. Keep one item.

With "keep one item", we keep the last item so users can still access downloaded files via the download manager e.g. to open the folder.

I wonder if a single option is enough. Would people like to use different mode for single download vs. batch download?

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/erase

**Comment by yfdyh000** [comment]
> I wonder if a single option is enough. Would people like to use different mode for single download vs. batch download?
> 
> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/erase

It may be enough for my needs. Even for a single download, the list of downloads panel can easily fill up, so it doesn't seem very common to keep a record of each file occasionally.
Don't clear if download errors occurred in the batch/group?
