### ISSUE TITLE
Displays the loading status and number in the title and favicon of picka page

### ISSUE THREAD

**Issue by yfdyh000** [eight04/image-picka#294]
partner #290. Sometimes picka pages takes a few tens of seconds or more for the images loading, adding favicons and title tooltips to identity may be nice?
For numbers, a total only or more is good. For the status, loading/loaded/has error is good? Even percentages?
Just a suggestion.

As a reminder, I suggest reverting/clean the title and icon before closing, otherwise they are recorded in the history.

**Comment by eight04** [comment]
Display status on the title should be pretty easy. It can be done along with progress bar tooltip:
https://github.com/eight04/image-picka/issues/291#issuecomment-1041944265

Favicon is harder:

1. Add two icons, one represents "loading" and one represents "completed".
2. Implement (1), and **show the progress on the icon** i.e. to generate the icon dynamically.

**Comment by eight04** [comment]
Most of them are fixed in #297. Open a new issue if you really want an icon.
