### ISSUE TITLE
Extension sometimes fails to download selected images (large amount of tabs)

### ISSUE THREAD

**Issue by xzorby** [eight04/image-picka#304]
This issue is difficult to reproduce since it only happens when I'm picking images from 100+ tabs, and even then it only happens maybe 5% of the time. I've used the extension successfully on up to about 800 tabs and usually it works like a dream. The chance of the issue occurring does seem to increase the more tabs I'm picking from, especially if it's 250+ tabs, so I try to stay below that number. My RAM usage typically stays below 80% and I've disabled cache partitioning, although I do still suspect the issue has something to do with memory. The tabs are all from one site, all the tabs have a single jpg of interest of about 30-1500 kB with a simple filename and all the other images on the page are ignored using [URL transforms](https://github.com/eight04/image-picka/issues/271). Example sfw gallery [here](https://fetlife.com/users/4329473/pictures) (note: nsfw website that requires signing up).

Usually what happens when this occurs is that I click "Save xx/xxx", then the extension closes and the tabs I've picked from all close as expected. However, none of the images are actually downloaded. I can use the extension as normal afterwards, except again no images are sent to downloads. There is usually no error message, so I don't always notice straight away that images are no longer being downloaded. Restarting Firefox fixes the problem.

Occasionally I do get an error message when clicking "Save", and then the extension does not close. The error message simply says "Error: an unexpected error occurred". When I click "Save" again, the extension closes, but no images are downloaded, and iirc only part of the tabs are closed. Then when I try to use the extension again, it works as above (no more errors, but nothing is sent to downloads), although I'm not sure if it's exactly the same problem. 
![Screenshot from 2021-11-27 22-05-06](https://user-images.githubusercontent.com/93467295/168899586-ab1bf87d-f15b-4d00-b46e-73889a94e962.png)

Is this a memory issue? Is there a way to at least notify the user that images are no longer being sent to downloads and that the extension/browser needs to be reloaded?

OS: Ubuntu 20.04.3 LTS
Browser: Firefox 100.0 (64 bit)

**Comment by eight04** [comment]
Yeah that sounds like a memory issue. Could you try [image_picka-0.15.1.zip](https://github.com/eight04/image-picka/files/8765730/image_picka-0.15.1.zip)?

Note that you have to use Firefox Nightly in order to install extensions from zip. Also it is safer to test it in a different profile so your original data will be safe if something goes wrong.
