### ISSUE TITLE
When batch downloading images, folder is not created based on page title in the Image Picka folder

### ISSUE THREAD

**Issue by klehman775** [eight04/image-picka#306]
System

    OS name: Windows 11
    OS version: [e.g. 10]
    Browser name: Firefox
    Browser version: 104.0.2
    Extension version: 0.15.1

Bug description

Trying to download batch images but when attempted it just download all to the Image Picka folder in the Downloads folder instead of creating a folder based on the page title. I didn't change any from the default settings, so the default path when saving images is still, Image Picka/${pageTitle}/${index} -

Logs

N/A

**Comment by eight04** [comment]
I can't reproduce with Firefox 104 + Windows 10.

Can you test it again on a new Firefox profile? I think there are two cases:

1. The webpage doesn't have a page title.
2. There is another extension renaming downloaded files, trimming the folder.

**Comment by klehman775** [comment]
Looks like it's working. It may have been just the webpage that I was on.

Thanks
