### ISSUE TITLE
Which element is downloaded from a <picture> element?

### ISSUE THREAD

**Issue by vigilantesculpting** [eight04/image-picka#307]
Background:
Some websites will use a &lt;picture&gt; element with a number of different &lt;source&gt; elements, which allows the browser (desktop vs mobile for example) to display the appropriately scaled image to the user for that picture.
As a fallback, the picture element always has an &lt;img&gt; element as a last resort, typically with the original resolution image.
Image Picka seems very capable of downloading these picture element images (the feature was added in 0.9.0 according to the changelog).

Question: Right now it seems that Image Picka will download the first &lt;source&gt; image (usually the lowest resolution one) when presented with a &lt;picture&gt; element. Is it possible that it can always download the &lt;img&gt; element instead?

EDIT: fixed up the brackets in the text

**Comment by eight04** [comment]
https://github.com/eight04/image-picka/blob/6a05e976ea111ab6a5ea719cd176071c1a0caf39/src/lib/image-util.js#L57-L62

We should probably collect all sources and find the largest one.

**Comment by vigilantesculpting** [comment]
I'll see what I can do to help, with the debugger.
