### ISSUE TITLE
You could add these new functions 

### ISSUE THREAD

**Issue by 7R4C341** [eight04/image-picka#308]
- add height and width limit. example x=1024px
if(image>=1024px and image<=1024) only download images of 1024.

- add to exclusion and inclusion list "multiple".  (url include) url-image3,url-image4, url-image7

**Comment by eight04** [comment]
> * add height and width limit. example x=1024px
>       if(image>=1024px and image<=1024) only download images of 1024.

Duplicate of #196.

> * add to exclusion and inclusion list "multiple".  (url include) url-image3,url-image4, url-image7

It is possible to include different words with OR operator:
```
url-image3|url-image4|url-image7
```
https://www.ocpsoft.org/tutorials/regular-expressions/or-in-regex/

**Comment by 7R4C341** [comment]
ok
