### ISSUE TITLE
Images saved in different format then "save page as complete" operation in browser.

### ISSUE THREAD

**Issue by bumbaras** [eight04/image-picka#319]
Not sure if is it "image picka" fault but I have found a site where images are saved as JPG with quality lower than 100
instead of webp images which are displayed on page, which are saved with "save page as complete on" in browser, and even when clicked
on image picka thumbnail and opened in separated tab (also webp). But addon is always saving them as jpg. I have removed default extension jpg in options but without success. If i take links from "copy links" button, the links will also give webp images. And quality in link parameters is set for 100.
https://scyllascans.org/read/marriage_of_convenience/en/0/1.0

**Comment by bumbaras** [comment]
Also it is possible to grey save button in addon to the moment the addon finished operations like caching files? Because on mentioned site the images are long height strips, and i see how the thumbnails are drawing even after green bar of analyzing dissapeared on top of page and i am not sure if clicking save in this moment will give me whole images (images are still drawing on thumbnails), or maybe it is safe to wait some more time ...

**Comment by eight04** [comment]
> webp images which are displayed on page

The website displays `.jpg` to me:
![image](https://user-images.githubusercontent.com/1324510/206729617-0d34ba78-b4ed-47d4-b2a6-cf87f8e9687f.png)

> i am not sure if clicking save in this moment will give me whole images

Yes it does.

> (images are still drawing on thumbnails)

Thumbnails are hidden when it is not seen to reduce memory usage. Therefore you may experience a "loading" if the image is pretty large.
