### ISSUE TITLE
Filename pattern variables broken in v0.16.0

### ISSUE THREAD

**Issue by jbao161** [eight04/image-picka#322]
Use of ${dateString} in filename pattern produces "failed to evaluate dateString. The result is undefined" error. 
Same error for {index} and {date}. Possibly others.
In the past there was a function _(e) in background.js that returned the dateString that could be modified to produce a custom dateString. It seems to have vanished.

**Comment by eight04** [comment]
I can't reproduce. What is your browser? Which image did you try to download?

**Comment by jbao161** [comment]
Error happens on any image download with drag and drop. (For example: https://static.fjcdn.com/pictures/Toaster+cat_fbcb36_3338685.jpg). Tested on latest Google Chrome Version 109.0.5414.75 (Official Build) (64-bit), latest Firefox Developer 110.0b2 (64-bit). 

Extension version [v0.15.1](https://github.com/eight04/image-picka/releases/tag/v0.15.1) does not have this error.

**Comment by jbao161** [comment]
Error does not happen when right clicking image -> Image Picka ->Pick Images -> Download options -> Save.
Seems to be an issue with the "Download with drag-n-drop", "Download with single click", "Download with double click", and "Show a download button on hover" features.
