### ISSUE TITLE
Often crash batch saving images -> but only the first time

### ISSUE THREAD

**Issue by Jugibur** [eight04/image-picka#324]
I currently use this great plugin to backup the daily new Midjourney Showcase, for example. These are mostly 100 images. 
Unfortunately, both the standard file pattern and my individually chosen one keep crashing. This is shown by the fact that the tab is simply closed. Then only a handful of images have been saved.
If I then restart the process a few seconds later, batch saving almost always works smoothly.
I also use the two options under "Advanced" in the settings.

My current file pattern: Image Picka/${pageTitle}/${dateString}/${name} - ${alt}${ext}
Im using Firefox 109 on macOS Ventura (13.2)

**Comment by eight04** [comment]
Before saving, you should be able to see how many images will be downloaded on the "save" button. Does it match the actual number of downloaded images?

**Comment by Jugibur** [comment]
No, most of the time it does not match. 
It says ie.: "Save (100/115)",
then after saving often (in case of MidJourney) only 97 images saved.

**Comment by eight04** [comment]
Did you see any error in your downloads history (Ctrl-J)? What about the number in downloads history?

**Comment by Jugibur** [comment]
Yes, most of the time with the filename "grid_0_640_N - .webp"
After the dash I have a pattern string for saving the alt tag of the image. So may be it could be an error if two images with the same file name are saved (MidJourney always uses the same filename, only different paths).
I have now added an index variable at the first position. The test batch download after that works flawlessly. But I will observe this and report it in a few days.

**Comment by Jugibur** [comment]
Think the problem is solved now, because so far all 100 images in the MidJourney Showcase have always been downloaded without a crash. So it was probably due to duplicate file names, which has now been bypassed in my settings by adding an index. Thanks for your efforts!
