### ISSUE TITLE
alt tag is not always saved (the first time saving)

### ISSUE THREAD

**Issue by Jugibur** [eight04/image-picka#327]
Hi,
(as mentioned before) I download the MidJourney showcase every day and by now there are no more crashes. However, there is the phenomenon that almost always not all alt tags are written into the file name. I have configured this in the settings: 
`Image Picka/${pageTitle}/${dateString}/${index}-${name}-${alt}${ext}`

If I then download all images a second time, it works 99% of the time for all 100 images in that showcase.

I am surprised that the browser may not have read all alt tags the first time, but why is that?  I always wait until everything is completely loaded, but that does not fix the error the first time I save.

**Comment by eight04** [comment]
Do you have a link to Midjourney?
