### ISSUE TITLE
Possibly copy URL's with space instead of new line

### ISSUE THREAD

**Issue by remlap** [eight04/image-picka#329]
Hi is possible to copy URL's with a space instead of a new line?

Thanks

**Comment by eight04** [comment]
Yes. You just have to change this line
https://github.com/eight04/image-picka/blob/9a71160c25788978ba264ad34cf4e5cff24a919d/src/picker.js#L142
to
```js
			input.value = getUrls(getImages()).join(" ");
```

However, I think it should be easier to replace new line with space using a text editor.
