### ISSUE TITLE
[Feature request] open in new tab by middle mouse click

### ISSUE THREAD

**Issue by derdershat** [eight04/image-picka#334]
Is there a chance that you could add an open in new tab by middle mouse click option?
I often check the image by opening in a new tab before I download and an option for this would be very useful.

**Comment by eight04** [comment]
Do you mean to middle-click thumbnails during batch download?

**Comment by derdershat** [comment]
![Unbenannt](https://github.com/eight04/image-picka/assets/33583670/aa5cbde4-7dca-4eff-b5f9-4205780ef5bd)

yes in the main window where I can choose the found images.

**Comment by derdershat** [comment]
Thank you very much for this implementation. Works very good!
