### ISSUE TITLE
BLOB objects

### ISSUE THREAD

**Issue by bumbaras** [eight04/image-picka#335]
I will reopen the request to add support for images saved as blob objects.
Not firefox and chrome either can download them directly - chrome has option to download such image but it doesn't work.
As i understand blob objects are a code which is required to run to show picture. Somehow browsers can display the image correctly so maybe can it be fetched from cache or sth like that?

There was some tip to get them in chrome with developer mode, but with much struggles i was able to get only few of them. With more than few pictures on site it is discouraging to use this method. With FX I couldn't get a single image.

**Comment by eight04** [comment]
URL?
Browser version?

It works fine with our own test case on Firefox Nightly 120.0a1
https://github.com/eight04/image-picka/blob/9a71160c25788978ba264ad34cf4e5cff24a919d/test/frame.html#L7

**Comment by bensoc1** [comment]
hello, 
i've been using your extension for a while and it worked fine until today on this website :
https://www.japscan.lol/lecture-en-ligne/level-up-with-skills/39/1.html
nothing appear anymore they seem to have put blob objects ? 
 i tried to dl on firefox version 120.0.1

**Comment by eight04** [comment]
> https://www.japscan.lol/lecture-en-ligne/level-up-with-skills/39/1.html

I got a 404 page:
![image](https://github.com/eight04/image-picka/assets/1324510/4299341d-5696-48c0-895d-958daf743766)
