### ISSUE TITLE
Slowdown during download

### ISSUE THREAD

**Issue by winteryokai** [eight04/image-picka#343]
I've just added the latest release of picka onto my firefox yesterday, and it was working like magic downloading about 100 images in less than 10 seconds, so I recommended the same to a friend and the same was happening. but now it's lagging and to download only 20 images it takes more than 30 seconds for the both of us, though we've been on different parts of the world so I don't believe it's a connection issue. Prior to us getting the latest version it was also taking quite a bit to get the images needed, but after reaching heaven with such a speed to download we don't want to go back to the same slow download. Is there anything we can do on our end?

**Comment by eight04** [comment]
1. Try disabling network partition (https://github.com/eight04/image-picka/issues/270) so the extension can use the cache more efficiently (less secure).
2. Try changing your IP address. It is possible that the website got too much traffic from your pc and decided to limit your connection.
3. Try downloading at different times of day e.g. morning/night.

If you want to install old versions of Image Picka:
https://addons.mozilla.org/zh-TW/firefox/addon/image-picka/versions/
But I don't think it's relevant.
