### ISSUE TITLE
Illegal filename

### ISSUE THREAD

**Issue by eight04** [eight04/image-picka#347]
https://bugzilla.mozilla.org/show_bug.cgi?id=1898498

Should we create a test to find all illegal characters?

**Comment by Djidam** [comment]
Since the last update of firefox (v127.0), firefox throws an illegal character error when downloading files, and so nothing is downloaded.
I use this pattern for naming the files : ${pageTitle}/${index}.jpg

I use another addon, it uses pagetitle for naming the file, but no error with the last update of firefox (https://addons.mozilla.org/en-US/firefox/addon/save-text-to-file/) ?

**Comment by eight04** [comment]
save-text-to-file seems to use a native app to write data to the disk so it won't be affected by Firefox update.

**Comment by Djidam** [comment]
I have not install that local app. By default, files are saved in the download directory used by Firefox. If you wish to save them elsewhere, then you need the local app.

**Comment by eight04** [comment]
![image](https://github.com/eight04/image-picka/assets/1324510/5932b341-389a-481e-b97d-7dcad01160a5)
I can also reproduce this bug with save-text-to-file.

Maybe the filename doesn't include illegal characters when you save the text?

**Comment by Djidam** [comment]
Hmm
On the website I use both addons, one for text, yours for images (love it actually). Both with pageTitle. The pageTitle has those 3 characters . - !
The file for the text is saved, but I get the error for the images directory.
I'll use your addon in chrome, I tested my setup and that will do the job.

**Comment by eight04** [comment]
What is your OS and Firefox version? I can't reproduce on Windows 10 + Firefox 129.

BTW, you can preview the filename by hovering on the file pattern in batch download:
![image](https://github.com/eight04/image-picka/assets/1324510/4b87c09b-bab7-4b11-916d-32b63202ebb0)

**Comment by eight04** [comment]
https://github.com/eight04/webext-illegal-filename

**Comment by Djidam** [comment]
Windows 10 and firefox 127.
I tried to figure out what causes the error and I managed to reduce the string to: 1. A\1.jpg
I don't know why but if I have spaces after a dot, then firefox throws an error (the space can be right after the dot or it can have characters between, like 1.1 A\1.jpg)
![image](https://github.com/eight04/image-picka/assets/32293294/2a6ffe2e-92ab-4dee-8cfe-d0d61fe5a186)
![image](https://github.com/eight04/image-picka/assets/32293294/6cc72e3f-a3f1-4ebe-b96e-458450b1003f)

**Comment by brazenvoid** [comment]
I am also having this issue with the character | in the page title. It used to work completely fine before but now any page title with an illegal character does not work.

**Comment by brazenvoid** [comment]
Correction it is as @Djidam says, it only fails when there is a dot and a space in the name! How odd!

**Comment by eight04** [comment]
Link to the dot and space bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1903780

**Comment by brazenvoid** [comment]
@eight04 isn't there some way you can make your users vote on the report at bugzilla, like put a message on the addon page or something so it gets prioritized? I don't think the single vote that I added would make a difference...

**Comment by brazenvoid** [comment]
If someone wants a workaround, a simple userscript can do the job with one line of code. Here is what I am using:

```
// ==UserScript==
// @name         Firefox Download Bug Workaround
// @namespace    brazenvoid
// @version      1.0.0
// @description  Workarounds the download bug that does not allow a dot and a space in the filename
// @author       brazenvoid
// @match        *
// @grant        none
// ==/UserScript==

document.title = document.title.replaceAll('. ', ' ')
```

**Comment by brazenvoid** [comment]
@Djidam Well it works for my needs. I did update it a bit:

```
// ==UserScript==
// @name         Firefox Download Bug Workaround
// @namespace    brazenvoid
// @version      1.0.2
// @description  Fixes the download bug that does not allow a dot and a space in the filename
// @author       brazenvoid
// @match        https://[your site]/*
// @grant        none
// ==/UserScript==

document.title = document.title.replaceAll('. ', ' ').replaceAll('%', '').replaceAll('.', '-')
```

Replace `[your site]` with the domain you want it to work on.

**Comment by hdd1013** [comment]
Until the issue is fixed, perhaps we could add an option that strips all special characters from the pageTitle? Even apart from the bug it could be useful if you want to remove any potentially illegal characters from the path in case you want to set up a further pipeline that runs on the computer after the download.

**Comment by brazenvoid** [comment]
Yeah, it does seem that the Firefox developers don't really have any input from extension API devs when making changes in their internal functions especially when they are shared with them. 

The bug discussion has now gone to figuring out how or to even make provision for the extension API's specific needs. They make it sound as if the extension developers were using it wrongly after changing the scope of the problematic internal function. 

It is eerily similar to the blame games I experience among developers when they are caught being irresponsible.

**Comment by brazenvoid** [comment]
@eight04 Can you please mention in the bugzilla thread for dot and space bug, what you want from the download.sanitize API. The developer thinks that you only want directory validation and not file validation. 

Quite an odd understanding in my opinion. 

I think that you want complete path validation including the directory and filename.

**Comment by eight04** [comment]
> strips all special characters from the pageTitle?

It is possible to do something like
```
Image Picka/{pageTitle.replace('.','_')}/{...
```
Since %, spaces and dots are usually valid characters, I'm still not sure if we should escape them by default.

**Comment by eight04** [comment]
@brazenvoid I think they are going to the right direction.

They will need 2 API, one for validating filename and one for folder name.

Now we only have one API. It is used to validate both filename and folder name. After ff127, it gets more strict to file extensions by disallowing spaces. While it makes no sense to folder name since there is no extension.

It seems that they want to create a new option in the API to support both cases.

**Comment by eight04** [comment]
Another case that may also leads to an invalid filename:
When the filename includes a dot and a space while the the filename is too long and get trimmed.
