### ISSUE TITLE
cannot read properties of undefined (reading url)

### ISSUE THREAD

**Issue by myrat** [eight04/image-picka#348]
This notification pops up when I try to run the extension:

_cannot read properties of undefined (reading url)_

---
(Google Chrome 126.0.6478.127, win 10 x64)

**Comment by eight04** [comment]
When did you get this popup e.g. after clicking an button, opening a tab, etc?

**Comment by myrat** [comment]
It gives error in version 17, but version 16 works without error, but can't split downloads by folders, directly to Downloads  folder.
For example:
https://www.behance.net/gallery/90288143/Central-Park?tracking_source=project_owner_other_projects
