### ISSUE TITLE
Can't Save Images From More than 180 Tabs (1 image per tab)

### ISSUE THREAD

**Issue by brazenvoid** [eight04/image-picka#349]
Simply the extension experiences an irrecoverable crash when attempting to save more than ~180 images from 180 tabs. 

It does not show any error.

It downloads them in the extension page just fine. 

To recover I have to force an extension reload through enable/disable cycle in Firefox.

There is another odd behaviour with such. If for example I initiate the action of picking all the images, any cancellation and initiation for a subset does not work. It always resumes the picking for the whole group.

**Expected behavior**
It downloads all images, regardless of how many. 

**Environments (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 128
 - Extension Version: 0.17.0

**Comment by eight04** [comment]
Maybe it's an out of memory crash.

Could you see any memory spike in task manager after clicking the "save" button?

**Comment by brazenvoid** [comment]
No change in memory use.

Also I forgot to mention, not a single image actually gets saved and if the option close tabs is checked, some ~70 don't get closed.

Very rarely it does throw an unexpected error confirm box and in this case the picka tab remains on screen though it does nothing.

**Comment by brazenvoid** [comment]
And another thing, I think something changed in Firefox as it did work for as many images as I tried with it before.

**Comment by brazenvoid** [comment]
No, no system tab open. 

The UI does show all the thumbnails, doesn't that mean they were downloaded already? But yes it doesn't make sense, the memory doesn't go up at all.

**Comment by eight04** [comment]
Since the picker remains opened, are you able to see any error in F12 console after clicking the save button?
