### ISSUE TITLE
general.useragent.locale doesn't work

### ISSUE THREAD

**Issue by eight04** [eight04/image-picka#35]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization#Testing_out_your_extension
```
D:\Dev\image-picka>npm start -- --pref general.useragent.locale=zh-TW

> image-picka@0.5.2 start D:\Dev\image-picka
> web-ext run "--pref" "general.useragent.locale=zh-TW"

Running web extension from D:\Dev\image-picka
Setting custom Firefox preferences: {
  "general.useragent.locale": "zh-TW"
}
Use --verbose or open Tools > Web Developer > Browser Console to see logging
Installed D:\Dev\image-picka as a temporary add-on
The extension will reload if any source file changes
Press R to reload (and Ctrl-C to quit)
```
![image](https://user-images.githubusercontent.com/1324510/33983185-3177ae7c-e0ee-11e7-8100-e07d6893a816.png)
Only the message used in manifest is changed.

Now I install [portable Firefox](https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./) in order to test different locales.

**Comment by yfdyh000** [comment]
This looks work for me. 

`optionCustomIconLabel` and `optionCustomIconColorLabel` seems to not applied.

**Comment by eight04** [comment]
They are added after #32 is merged.

Here you can find them on Transifex:
https://www.transifex.com/image-picka/image-picka/translate/#zh_CN/messagesjson/129172120?translated=no

**Comment by yfdyh000** [comment]
This seems to be a timing conflict, sometimes not working.

I checked it on a local git repo, but it does not seem to work.

**Comment by eight04** [comment]
It is ready for use now:
![image](https://user-images.githubusercontent.com/1324510/33989876-09440020-e104-11e7-9257-5536d036a737.png)
I'm going to release 0.6.0.

**Comment by eight04** [comment]
This option had been changed to `intl.locale.requested` but still, i18n API doesn't respect it.

**Comment by eight04** [comment]
So this option only works if:

1. Use Firefox stable.
2. Install required [language packs](https://addons.mozilla.org/zh-TW/firefox/language-tools/).
