### ISSUE TITLE
Locale dependent CSS contains garbled text

### ISSUE THREAD

**Issue by eight04** [eight04/image-picka#36]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization#Locale-dependent_CSS
![image](https://user-images.githubusercontent.com/1324510/33983386-faa1bc7a-e0ee-11e7-8434-6ac7d6a03c7a.png)

I guess we should just retrieve the message from i18n API.

**Comment by yfdyh000** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1389099

**Comment by eight04** [comment]
It seems that it is fixed in Firefox 62.
