### ISSUE TITLE
Does not download image from tumblr.com

### ISSUE THREAD

**Issue by ksadom** [eight04/image-picka#38]
Error in downloading. Please fix.

**Comment by eight04** [comment]
I can't reproduce. What is the error? On which URL?

**Comment by ksadom** [comment]
Can you download image from the following link **using button on hover**? 

http://coffeeandlessonplans.tumblr.com/post/168372050088/ksubied-checking-out-all-new-followers-x


try this and advise. Thank

**Comment by eight04** [comment]
Confirmed. Try turning on the option "Download images from cache".

I would like to find out why Firefox failed to download the image, so let's keep this issue open.

**Comment by eight04** [comment]
@temporalix Your images are not downloaded from `tumblr.com` but `konachan.com`. Please report your problem in a new issue.
