### ISSUE TITLE
Duplicated images

### ISSUE THREAD

**Issue by ksadom** [eight04/image-picka#39]
When I save an image **twice** using button on hover the image saved duplicated with same file name and counter number (1),(2)..etc.

Please add option to avoid duplicated file name . Thank you

**Comment by eight04** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/FilenameConflictAction

There are 3 ways to handle conflicted filename:

1. `uniquify` - adding `(1)`, `(2)` to the end of the filename.
2. `overwrite` - replace the old file with the new one.
3. `prompt` - ask the user whether to use `uniquify` or `overwrite`.

Seems that there is no way to **avoid** it (cancel the download), also the `prompt` option is not supported by Firefox:

https://bugzilla.mozilla.org/show_bug.cgi?id=1425515

Do you think that it is worth it to add an option to overwrite the old file?

**Comment by ksadom** [comment]
Hi Sir,
Sadly that Firefox not supporting prompt option. So yes I think overwrite old file is better than duplicated. I wish you add this option. Thank you

**Comment by eight04** [comment]
Added in 0.6.1.
