### ISSUE TITLE
Feature Request: Tabs to the right

### ISSUE THREAD

**Issue by john5698** [eight04/image-picka#4]
It would be very helpful if this addon could include the ability to save all images meeting the filter requirements (eg size) on the current tab OR any tab to the right of the current tab

**Comment by eight04** [comment]
IIRC, Image Picker has this option, but I don't know how to use this feature so didn't implement it. I can think one of the use case is to download all images from multiple pages at once if the site contains pagination:
![image](https://user-images.githubusercontent.com/1324510/33001871-97576f54-cdeb-11e7-9bbd-8ef317bdfa33.png)
By opening all links to the background.

But there are some problems:

* Should current tab be included?
* Which page should be used for title/URL?

Also I would like to know how you may use this feature.

**Comment by john5698** [comment]
Yes, I was hoping this would be included as a feature as Image Picker does not seem to be moving to WebExtensions. 

Should current tab be included? Yes

Which page should be used for title/URL?
I do not really have an opinion on the naming

These are a few use cases, I am sure there are others:

**Use case one:**
When a web page presents a list of image thumbnails that link to the full size image (or a page showing the full image) and:

- You only want a selection of images and the URLs contains random GUIDs making the URL not guessable
- The link links to another webpage that shows the full sized image, rather than the link linking directly to the full image.

In these cases, middle clicking the links tend to open them in the background (or can be set to in Firefox options)

**Use case two:**
When the output of one extension is a selection of tabs. I find that a task can often be completed by combining multiple extensions. 

1. Open a selection of links in tabs using an extension like "Open Links in Tabs" (can not find the one I used to use)
2. Use an extension like this one to select the full sized images (based on resolution / file size / type)

**Comment by eight04** [comment]
Added in 0.4.0.
