### ISSUE TITLE
Extract substring from variables

### ISSUE THREAD

**Issue by eight04** [eight04/image-picka#40]
https://addons.mozilla.org/zh-TW/firefox/addon/image-picka/reviews/1008492/

I think we can

* Add some kinds of transform/filter syntax: `${variable|slice:5,10}`. We had implemented this in [inline-js](https://github.com/eight04/inline-js)
* Parse string methods: `${variable.slice(5, 10)}`
* An ultimate method is to eval the string. It might be handy to manipulate `index`: `${index + 1} ${index.padStart(3, '0')}`. I think `eval` is not permitted in background page. If we really want to do this, maybe we can create a new tab + worker as sandbox.

----

Another solution is to keep Image Picka simple and add ability to extract filename from images's attributes, so users can customize the filename programmatically with userscripts.

But it can't modify `index`.

**Comment by eight04** [comment]
https://github.com/olstenlarck/es6-template
https://github.com/souldreamer/string-template-parser
https://github.com/medikoo/es6-template-strings

**Comment by eight04** [comment]
https://www.npmjs.com/package/static-eval

**Comment by eight04** [comment]
I'm going to use https://github.com/donmccurdy/expression-eval

* Parse expressions and evaluate it with a context object, without unsafe eval.
* It uses jsep, which is liter than esprima.

We should add an advanced setting `Use expressions in filename pattern` to enable this feature. Also doc this in README.md.

**Comment by eight04** [comment]
Added in 0.6.1.

**Comment by FireHerman** [comment]
Excellent! Thank you so much.
