### ISSUE TITLE
Customize the position of the download button

### ISSUE THREAD

**Issue by eight04** [eight04/image-picka#43]
https://addons.mozilla.org/zh-TW/firefox/addon/image-picka/reviews/1017606/

**Comment by ksadom** [comment]
This is good idea. The button should be inside image frame.

**Comment by eight04** [comment]
I might add two options:

1. `Horizontal position`: Possible values are `Outside left`, `Inside left`, `Center`, `Inside right`, and `Outside right`.
2. `Vertical position`: Possible values are `Outside top`, `Inside top`, `Center`, `Inside bottom`, and `Outside bottom`.

The default value is `Inside left` + `Outside top`.

Also, since the button may cover the image, maybe it needs some transparency.

**Comment by ksadom** [comment]
Yes, thank you.

**Comment by eight04** [comment]
Added in 0.6.1.
