### ISSUE TITLE
Excluding a domain.

### ISSUE THREAD

**Issue by ksadom** [eight04/image-picka#44]
I hope there is an option to exclude some domains that not need to appear download button. Thanks

**Comment by eight04** [comment]
Interesting. I think there are 2 ways to solve this:

1. Use config system having some kinds of "domain scope", so users can change the settings individually according to the domain.
2. Put a code box under "Advanced" section, including multiple lines of domains which we don't want to use download button (or just disable "Download Single Image" feature on those domains).

(1) is actually another feature. The only setting which users might want to change it individually is `filenamePattern`. If you have a long list of domains, changing settings on each of them could be a trouble.

(2) is just a simple exclusion list, which should be easy to implement,

**Comment by ksadom** [comment]
I think This way is better.

> Put a code box under "Advanced" section, including multiple lines of domains which we don't want to use download button (or just disable "Download Single Image" feature on those domains).

**Comment by eight04** [comment]
Added in 0.6.1.
