### ISSUE TITLE
Add command shortcut to toggle Image Picka

### ISSUE THREAD

**Issue by ksadom** [eight04/image-picka#52]
Hi,
I hope you add a new option under "pic image from current tab". Option to disable/enable Image Picka.
Some time if we browsing many sites we don't want to bother by the download icon on that sites images. So better to have option to disable/enable Image Picka temporary by on click.

**Comment by eight04** [comment]
I think we need a way to indicate whether the extension is currently in a disabled state. Maybe use an "x" in the badge text?

**Comment by ksadom** [comment]
Yes I think so "X" is good option. Thank you

**Comment by eight04** [comment]
> Maybe use an "x" in the badge text

I think that the badge text probably will be used to implement a download counter in the future, so I currently use a checkbox for it. What do you think?

![image](https://user-images.githubusercontent.com/1324510/35072801-1f8a3560-fc21-11e7-9788-32e90c12a383.png)

**Comment by ksadom** [comment]
Hi friend, this is good idea also.

**Comment by eight04** [comment]
https://addons.mozilla.org/zh-TW/firefox/addon/image-picka/reviews/1035388/

**Comment by eight04** [comment]
Added in 0.7.0.
