### ISSUE TITLE
"Pick Images from Tabs to the right" picks also from the current tab

### ISSUE THREAD

**Issue by Esoppant** [eight04/image-picka#54]
"Pick Images from Tabs to the right" picks images from tabs to the right + the images in the current tab. Is it meant to be that way? If so, the naming sounds a bit misleading (and an "pick from only tabs to the right" option would be useful to avoid always selecting the leftmost desired tab on the right of the current tab)

**Comment by eight04** [comment]
Yeah, it was discussed in #4. However, I can think that in some situations, it would be useful to exclude the current tab (e.g. excluding thumbnails in the current tab). How about to have 3 commands:

* Pick images from current tab
* Pick images from current tab + right tabs
* Pick images from right tabs

@john5698

**Comment by Esoppant** [comment]
I agree. The spiritual predecessor of this add-on "Save Images" also had those three options.
(It also had a "tabs to the left" version which I never used, and which felt rather useless given how tabs open to the right by default)

**Comment by john5698** [comment]
After a bit of thinking, I agree with this case. Firefox has the option "Close tabs to the Right" which does not close the current tab and this sets the users expectations for similar named functions.

**Comment by eight04** [comment]
Added in 0.7.0.
