### ISSUE TITLE
Remember index from last batch download and continue from there.

### ISSUE THREAD

**Issue by ThisWillDoIt** [eight04/image-picka#59]
Right now when downloading a batch to a folder I can use just their index with this expression:
"Image Picka/${index}${ext}"
which gives me filenames like 1.jpg; 2.jpg; 3.jpg

When I download the next batch it duplicates all filenames to 1.jpg; 1(1). jpg, 2.jpg; 2(1).jpg,...

It would be nice if the extension could remember where it left of in that folder and continue with 4.jpg, 5.jpg etc instead.

**Comment by eight04** [comment]
I don't think it is a good idea. If we reuse the index from the last time, we need another command to reset the index.

How about download images into a separated folder to avoid collision?
