### ISSUE TITLE
number pic 

### ISSUE THREAD

**Issue by MarceloTDF** [eight04/image-picka#61]
hi number of pic  instead of it 1,10, 2, 20, 3, // could be  001, 002, 003 .... 010, 020

**Comment by eight04** [comment]
I don't understand what do you mean.

**Comment by MarceloTDF** [comment]
when save the image instead of it  name1, name10, name2 could be name001, name002, .... name010

**Comment by eight04** [comment]
Do you mean to zero-pad the numbers inside ${name} variable?

**Comment by MarceloTDF** [comment]
if you can.  if not, no problem

**Comment by eight04** [comment]
The problem is that I'm not sure what do you mean. Do you mean to zero-pad the numbers inside ${name} variable?
