### ISSUE TITLE
Option to turn off error prompt

### ISSUE THREAD

**Issue by ardengh** [eight04/image-picka#65]
When i manually cancel the download of an image (pressing escape at the Save As window), the error box always pops up at the bottom right of the browser.  Feels like an option to opt-out of getting this error prompt would be more user friendly.  If I escape out of an image save, I'm already aware that I'm cancelling my download, the error box seems like redundant info.  It forces the user to go click and close another window and interrupts the user experience.

Thanks for the great work, I'm loving this extension!

**Comment by eight04** [comment]
https://stackoverflow.com/questions/48425109/detect-when-saveas-dialog-is-canceled

I think we can determine the error from the message then ignore it, but we have to ensure the error message is persistent in different environments (locales).

**Comment by eight04** [comment]
Fixed in 0.7.1.
