### ISSUE TITLE
Absolute path?

### ISSUE THREAD

**Issue by TerraD** [eight04/image-picka#70]
Why cant I specify an absolute down loadpath?

I don't store any downloads in C:\Users\MyUser\Downloads. I want them to be right in my project folder.

**Comment by eight04** [comment]
[It's a restriction of webextension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/download#Parameters). Extensions can only download files into the default download folder in Firefox 57+.
