### ISSUE TITLE
Filename pattern ignored when grabbing from multiple tabs

### ISSUE THREAD

**Issue by RianGray** [eight04/image-picka#71]
I'm not sure if this is by design, or a glitch. If it is by design, this would be a feature request.

Currently when I choose to download images from more than one tab, image-picka creates only one folder by the first tab regardless of filename setup. For the reference, this is the pattern I am using: 
`${pageTitle}/${index} - ${name}${ext}`
I was expecting it to create different folders per page title, (or per tab, as long as the names are different) but this setup only creates one folder and consolidates all the images in that folder followed by continuing index.

It would be nice if image-picka would save it in different folders, perhaps with an option to either continue the index variable or not. Consolidating them as it is now can be easily done manually anyway.

**Comment by eight04** [comment]
Currently, here is how batch downloads work:

1. Grab the variables from the current page (pageTitle, pageUrl, etc).
2. Collect images from tabs (current tab/current tab + right tabs/right tabs).
3. Remove duplicated images and send the images to picker UI.
4. Choose which images to download.
5. Send the images to the downloader.

To implement the requested feature:

1. We have to isolate each tab in the picker UI. But what about the filter? A global filter doesn't make sense IMHO.
2. Collect the variables from each tab.
3. It may contain the same image in different tabs.

**Comment by RianGray** [comment]
I can't say if it would be doable, but applying one filter globally in this particular occasion(saving from multiple tabs) wouldn't cause much confusion. I don't think UI needs to revamped to separate images per tab, as long as users are aware they are seeing all of the images. Considering how it is display right now, I was under the impression each image file ran through the filter and the file pattern independently.

As for the duplicates, although I can't speak for all the users, I think most would have redundant systems/habit to check the duplicates. Easiest way for a user to do so would be changing the file pattern to include url and filename, so that if they choose to consolidate several folders, it would invoke duplicate name message and/or be visible to the user.
