### ISSUE TITLE
IFrame support

### ISSUE THREAD

**Issue by john5698** [eight04/image-picka#75]
It appears that image-picka is not able to download images when the images are inside an iframe. 

I was using image-picka to pull images from an internal website, but it does not find the images inside the iframe. The images are in a basic img tag inside the iframe.

**Comment by eight04** [comment]
If you enable `Add "Pick Images..." actions to context menu` in the options page, you can right-click *inside* the iframe. By selecting `Pick Images from Current Tab` command, it would only pick images from that frame.

Or, did you want to collect all images from each frames recursively?

**Comment by john5698** [comment]
I currently have "Pick Images from Current Tab + Right Tags" selected in the options. It does select Images from the Current Tab + Right Tags, but it does not include iFrames. 

I would think collecting all images from all frames recursively would make sense, or at least could be an option.

**Comment by eight04** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1454342

**Comment by eight04** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1454627

**Comment by eight04** [comment]
Added in 0.7.4.
