### ISSUE TITLE
Close Tab Single Image Download

### ISSUE THREAD

**Issue by chungomi** [eight04/image-picka#77]
eight04,

Would it be possible to add an option to close the tab after a single image download completes?  Ideally an option to close the tab (x) seconds after download completes.

Thank You!
Don

**Comment by eight04** [comment]
What is the use case for this feature?

**Comment by chungomi** [comment]
Sorry not following you.  I would like to have the tab automatically close after a single image download completes.

**Comment by eight04** [comment]
Closing the tab after drag-n-drop doesn't really make sense to me. I would like to know why you want to do that.

**Comment by chungomi** [comment]
So i dont have to close the tab manually:) The feature is present if you batch download, would it be possible to port into a single image download?

**Comment by eight04** [comment]
> i dont have to close the tab manually

I meant in which situation you would like to close the current tab after the download? Personally, when I want to download an image with drag-n-drop, I'm heading to the middle of the article and still reading after the download, so closing the current tab doesn't make sense to me.

> would it be possible to port into a single image download?

Sure, just add the following line:
```js
browser.runtime.sendMessage({method: "closeTab"});
```
around here:
https://github.com/eight04/image-picka/blob/2b772403274309cf0256bccea956cda776889b20/content/dragndrop.js#L207-L213

I don't think it is a valuable feature, you can just Ctrl+W/middle click on the tab to close the current tab. The reason that there is a "Close Tabs" option for batch download is that users may open multiple tabs at once and want to close them all after the batch download. "Close tabs" feature saves users from pressing Ctrl+W multiple times.

**Comment by chungomi** [comment]
Thanks. I will give it a try tonight.
