### ISSUE TITLE
Request for file name pattern implementation with drag n drop

### ISSUE THREAD

**Issue by chungomi** [eight04/image-picka#79]
Hi eight04,

Can you implement filename pattern for drag n drop usage?  I would like to use the following:

${dateString}{ext}

When I drag and drop, the actual filename is being pulled from the website. Due to the volume in my folder, i would simply just like the datestring as the name. i have another program which can find the duplicate if it is one.

I have attached screenshots of my settings, in case i am misunderstanding.

Thank You!

![capture2](https://user-images.githubusercontent.com/38556629/39066413-9660a400-449a-11e8-9fdd-78f07bd6b2bf.PNG)
![capture1](https://user-images.githubusercontent.com/38556629/39066414-96765d22-449a-11e8-8590-fbb771ec1eaa.PNG)

**Comment by eight04** [comment]
Your setting should work. When drag-n-drop, the extension uses the filename pattern under "Download Single Image" section.

**Comment by eight04** [comment]
You meant that you had already set the filename pattern to `${dateString}${ext}`? What is the version of your Firefox and Image Picka?

**Comment by chungomi** [comment]
59.0.2 64b Firefox
0.7.3 Image Picka

Yes, the screenshots were set prior to using dragndrop. The resulting file looks like it is using solely the title.

Thanks!

**Comment by eight04** [comment]
I can't reproduce it. Could you test it on a new profile? Instruction: https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by chungomi** [comment]
Will do.

**Comment by chungomi** [comment]
Created a test profile and installed only image picka-same issue.

**Comment by eight04** [comment]
Interesting. Try to:

1. Open the addon debugger. (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Debugging)
2. In the console, type `copy(pref.get())` and press Enter. This command copies your setting to the clipboard.
3. Paste the setting here.
4. If there is any message in the console, post it here too.

**Comment by chungomi** [comment]
{
  "browserAction": "PICK_FROM_CURRENT_TAB",
  "blacklist": "",
  "closeTabsAfterSave": false,
  "contextMenu": true,
  "customIcon": false,
  "customIconColor": "#000000",
  "enabled": true,
  "dragndrop": true,
  "downloadButton": false,
  "downloadButtonDelay": 0,
  "downloadButtonDelayHide": 500,
  "downloadButtonMinWidth": 64,
  "downloadButtonMinHeight": 64,
  "downloadButtonPositionHorizontal": "LEFT_INSIDE",
  "downloadButtonPositionVertical": "TOP_OUTSIDE",
  "isolateTabs": false,
  "filenameMaxLength": 128,
  "filenameConflictAction": "uniquify",
  "saveAs": false,
  "singleClick": false,
  "singleClickCtrl": false,
  "singleClickShift": false,
  "singleClickAlt": true,
  "srcAlternative": "data-src, data-gifsrc, gifsrc",
  "previewMaxHeight": 200,
  "urlMap": "",
  "useCache": false,
  "useExpression": false,
  "filePattern": "${dateString}${ext}",
  "filePatternBatch": "Image Picka/${pageTitle}/${index} - ${name}${ext}",
  "defaultExt": ".jpg",
  "defaultName": "unnamed-image",
  "minFileSize": 0,
  "minWidth": 10,
  "minHeight": 10,
  "matchType": "include",
  "matchUrl": "",
  "filePatternHistory": "[\"${dateString}${ext}\"]"
}
![debug](https://user-images.githubusercontent.com/38556629/39085582-7d7db648-454a-11e8-84fe-39d8f81f430a.PNG)

**Comment by eight04** [comment]
It seems that the setting is correctly saved `"filePattern": "${dateString}${ext}"`. Now I wonder if it is a bug in Firefox:

1. Go to the debugger, open the .js file `background/background.js`, find line 79 and left-click on the line number to create a breakpoint. At the top right, click on *Add watch expression*, type `filename` and press enter.
  ![image](https://user-images.githubusercontent.com/1324510/39085873-0fac860e-45bc-11e8-8c27-5d607c8cde1e.png)
2. Switch to the browser, open any page and download an image by drag-n-drop.
3. Switch back to the debugger and give me the watch expression and the call stack.
  ![image](https://user-images.githubusercontent.com/1324510/39085902-78f26796-45bc-11e8-923b-9ac71f8b239f.png)
4. Left-click on the line number 79 to remove the breakpoint and press F8 to stop debugging.

**Comment by chungomi** [comment]
Unless I am doing something wrong (and from screenshots you provided it looks pretty simple), i am unable to get the file name to appear in the debugger:

 I created the breakpoint on 79, added filename in the watch expressions and pressed enter. Opened several new tabes, dragged the images to my desktop-yet nothing is appearing as the filename (see attachment).
Am i missing something?
![call stack missing](https://user-images.githubusercontent.com/38556629/39086184-8a97c7f2-4553-11e8-8c5d-a7144b744e0a.PNG)

If I could get dragndrop to work with the datestring, imagepicka would fit my needs perfectly. Hell if you created a specialized (lite) version of image clicka which only uses dragndrop and the dateString I would be willing to reimburse you for your time!

Is the dateString using something in firefox or java like the following?

import java.text.SimpleDateFormat;
import java.util.Date;

public class Time2 {

  public static void main(String[] argv) {
    SimpleDateFormat f = new SimpleDateFormat("yyyyMMdd HHmmssSSS");
    System.out.println(f.format(new Date()));
  }
}

Thank You!

**Comment by chungomi** [comment]
Also, I am only experiencing the issue in dragndrop.  If i use one click, the button or ask me the date string works perfedctly.

**Comment by chungomi** [comment]
Sorry to have wasted your time.  However when i drop it to anywhere else in the browse or use dragndrop in conjunction w ask me everytime it is always defaulting to my downloads folder-which is not set in my imagepicka settings. 

You mentioned that it is based off of firefox's settings-which are set to ask me everytime also, but firefox never remembers the last save location (ive tried creating a new boolean and a couple different tricks i found on the net  to no avail).  It just defaults to my downloads folder.

As you know (from someone elses ticket submitted here) a bugfix was reuquested to firefox over 4 months ago and no action has been taken to resolve the issue. Could something be built in to imagepicka which would use windows save as (or a java save as) feature versus firefox's?

Thanks again!

**Comment by chungomi** [comment]
OR could drag n drop be modified to let you drag the image to a folder of your your choosing (overriding firefox's function)?

**Comment by eight04** [comment]
> a bugfix was reuquested to firefox over 4 months ago and no action has been taken to resolve the issue.

You can try to vote that ticket, although I'm not really sure if it helps.

> Could something be built in to imagepicka which would use windows save as (or a java save as) feature

No. Extensions has no right to interact with the system, so you must use something else to rename the file.

An easy setup would be to create a script that watches the download folder and detects if there is a new image. When a new image is created (downloaded), launch a dialog to ask a new filename.

A more complicated method is to create a download manager which could be interacted with [native messaging](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging) or [custom URI scheme](https://msdn.microsoft.com/en-us/ie/aa767914(v=vs.94)). After the download manager is installed, modify the extension to send the file to the download manager instead of Firefox downloader, hence you can control how/where to download the image.

> overriding firefox's function

AFAIK, Firefox doesn't provide this feature. However, I think it is nice to allow the extension to override this behavior (or maybe just the filename?). Maybe you can create a feature request on bugzilla.
