### ISSUE TITLE
An unexpected error occured

### ISSUE THREAD

**Issue by BlazerOfScenario** [eight04/image-picka#80]
Hi

I have this message => Error: An unexpected error occured
Url: https://fanfox.net/store/manga/26181/001.0/compressed/up000.jpg?token=5394374d7b739b2dbf0a75ef7cb8d56abdd83fe8&ttl=1524992400
filename: Image Picka/Isekai de Skill wo Kaitai shitara Cheat na Yome  ga Zoushoku Shimashita Gainen Kousa no Structure 1 - Read sekai de Skill wo Kaitai shitara Cheat na Yome  ga Zoushoku Shimashita Gainen Kousa no Structure 1 Online - Page 1/up000.jpg
I try to change the value in the minimum height, File size, try with Image Picka/${pageTitle}/${index} - ${name}${ext} and Image Picka/${pageTitle}/${index-1} - ${name}${ext} and with the image from the browser cache, try with 1028 as max length for the name, but nothing work.
This happen only with this file, a try on Fanfox ( Don't work, and Manganelo( work only for page 14-13), maybe the name?
Width : 0 Heigth : 0 File Size : 0 include URL : Regular Expression File
File Name Patern : Image Picka/${pageTitle}/${index} - ${name}${ext}

An idea ?

**Comment by eight04** [comment]
If you are using Windows, it is probably due to the maximum path length limitation. Try lowering the number of `Max length of the filename` option to e.g. 50.

**Comment by BlazerOfScenario** [comment]
It's working, thank you ! do you plan to add an " Select similar " " Select all " " Unselect all "function ?

**Comment by eight04** [comment]
> Select similar

What does it mean?

> Select all

All images are selected by default.

> Unselect all

Just click "Invert selection" button.

**Comment by BlazerOfScenario** [comment]
Select similar
What does it mean?
Sorry, english is not my first language so sometime, it's hard to explain thing ^^ 
Before I update my browser, i was using "Image picker 1.9.5 " and he had a option which allows to select automatically every image who look like the one you select ( Maybe he could recognize them by the size of the name ), that was something useful when i had to save some manga or webtoon for later. With that, I did not uncheck the logo or Read more by hand.

**Comment by eight04** [comment]
Here is the code that is used by Image Picker:
https://github.com/wesley-chen/imagepicker/blob/c982268a13f1f5f27251715e9b637ef652753e0f/srcExtension/chrome/content/controller.js#L500-L526

If two images are in the same folder, they are considered similar e.g. `http://example.com/folder/a.jpg` v.s. `http://example.com/folder/b.jpg`.

If this is what you need, you can try to type the folder name to URL filter.

**Comment by BlazerOfScenario** [comment]
Thank !
