### ISSUE TITLE
Saves as 1,2,3, instead of 00001, 00002, 00003

### ISSUE THREAD

**Issue by zachiles** [eight04/image-picka#81]
Saving with leading zeros would be useful in batch renaming.  Right now, it takes 1.png, 10.png, 100.png, etc... throwing all order out the window.

**Comment by eight04** [comment]
You can zero-pad the index by enabling "simple expression" option and changing the filename pattern to:
```
 Image Picka/${pageTitle}/${String(index).padStart(3,"0")} - ${name}${ext}
```

Mode information: https://github.com/eight04/image-picka#use-expression-in-filename
