### ISSUE TITLE
Running error on “shonenmagazine”

### ISSUE THREAD

**Issue by andla119** [eight04/image-picka#87]
eg:https://pocket.shonenmagazine.com/episode/10834108156629534907
![3 - 10834108156629535125-ad7771a83c816ae41fdd0d452f8f7266](https://user-images.githubusercontent.com/39298039/40049479-72f2927c-5867-11e8-9a51-261b5b50ba8e.jpg)

**Comment by andla119** [comment]
i know，this site uses some anti-piracy measures

**Comment by eight04** [comment]
It works as intend. The server sends broken images to the browser then fix it with JavaScript. Image Picka can only help you download images so you have to edit the image yourself.
