### ISSUE TITLE
Dot in path names not accepted

### ISSUE THREAD

**Issue by mrandreastoth** [eight04/image-picka#90]
My download paths are ".staging/image picka/${pageTitle}/${name}${ext}". This is a valid path in Windows yet Image Picka tells me the path contain invalid characters and so refuses to download. If I remove the dot then Image Picka doesn't complain, but, of course, then the download goes to the wrong folder. This issue applies to both single- and batch-downloads.

**Comment by eight04** [comment]
Interesting. I didn't know that leading dots cause errors. It is hard to say whether it is a bug or not, Chrome also throws invalid filename error.

**Comment by mrandreastoth** [comment]
I can save a file from Firefox without any issues. Also, dot files/folders on Windows are not hidden, only on UNIX/Linux. Even so, why shouldn't a user be able to save to a hidden folder? In fact, I can save to a folder starting with a dot which has the hidden attribute set from Firefox, so why shouldn't an extension be able to?

**Comment by mrandreastoth** [comment]
But isn't the check performed by Image Picka? Wouldn't the fix be to simply remove this check?

**Comment by eight04** [comment]
No, Image Picka doesn't check/validate leading dots. The error is thrown by Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1420005.

**Comment by mrandreastoth** [comment]
OK, this means there are two issues with Firefox as per my comment: https://bugzilla.mozilla.org/show_bug.cgi?id=1420005#c4.
