### ISSUE TITLE
Problem when downloading from tumblr.com

### ISSUE THREAD

**Issue by SaruhBaruh** [eight04/image-picka#92]
On certain blogs downloading images is not available, and I can download them in one picture.
Downloading from the cache is enabled. 
I'm logged in on the site.
For example http://mrsnakestone.tumblr.com/post/174704048956/mrsnakestone-just-some-quick-snarti-pics-yarti
In this case, another extension (Download Star) sees links to these pictures. 
Version Firefox 62.0a1

**Comment by eight04** [comment]
Those images are displayed in frames. To download them with the batch download, turn on the advanced option "Collect images from frames recursively".
