### ISSUE TITLE
Display Image Size

### ISSUE THREAD

**Issue by K-no-Uta** [eight04/image-picka#93]
Hello,

this page is so confusing, so I'm not sure if I'm right here. I tried to hand in a request over the "pull request" tab but couldn't get it to work, so I'm here. Sorry if it's the wrong place.

I wanted to ask if you could add labels displaying the image size. If such option exists, I didn't find it. It'd be a huge help to pick the right images before they get downloaded! 

This is it right now:

![1](https://user-images.githubusercontent.com/33396438/41260978-0a517b7e-6dda-11e8-9707-fe4d725cdceb.JPG)

And that is what I mean:

![2](https://user-images.githubusercontent.com/33396438/41260980-0a7e4564-6dda-11e8-82f0-1297a457246e.JPG)

That would be really great. Thank you.

**Comment by eight04** [comment]
The detailed information is shown when you hover on them.
![test](https://user-images.githubusercontent.com/1324510/41275919-0f56b8c0-6e55-11e8-973a-33b4d6b82bb9.gif)
Would it be better to add an option to display detailed information below the image like Google? There isn't a lot of space IMHO.

> I tried to hand in a request over the "pull request" tab but couldn't get it to work

The pull request tab is to work with [pull requests](https://help.github.com/articles/about-pull-requests/). If you [forked](https://guides.github.com/activities/forking/) a project and changed some code, you can send a "pull request" to the original author asking them to adopt your changes.

> Sorry if it's the wrong place.

No worries. You have done right.

**Comment by K-no-Uta** [comment]
Hello,

Thank you very much for your reply!

Yeah, I noticed that it's shown when hovering, but unfortunately, if I have two versions each picture, hovering and waiting and hovering and waiting takes long. And sometimes the differences are too small to use the size filter (especially since widths and heights are very different due to different formats). It would be incredibly helpful if I could see all sizes at once. That would also make it easier to determine a minimum width/height for the filter, too.

If it's me, it wouldn't even have to be below the picture. If space is an issue, it can be displayed in the lower part of the picture. But ofcourse, if its possible to add the size above or below as an optional setting, that'd be awesome! 😊

**Comment by eight04** [comment]
What do you think?
![image](https://user-images.githubusercontent.com/1324510/41415170-8200b2c4-701a-11e8-819e-5a59e31cb9a7.png)

**Comment by eight04** [comment]
I wonder if we should display the file size too. It's too complex IMHO:
![image](https://user-images.githubusercontent.com/1324510/41415319-e6957350-701a-11e8-86a6-6687200f6389.png)

**Comment by K-no-Uta** [comment]
Looks great, just that I recommend to make the outline grey (black or white could be OK, too). With either white or black font. Or you could make it a thin frame, rather than a background, if you'd want to keep the blue. Or you could tune the blue down to a lighter one. Simply, because it's visually better in terms of orientation for the eye. 😁 There it goes again, my "majored in design during high-school" self. Can't help but unsee these things. 😆 Sorry.
