### ISSUE TITLE
Context menu got ruined in the last update.

### ISSUE THREAD

**Issue by krstoserofil** [eight04/image-picka#97]
Up until know, after I click the IP icon, in the tab that emerges with images I could right click on the images and then have the option to View Image, Open Image in Tab, Search By Image, etc... 

Now its all gone, Firefox doesn't recognize them as images, and I HAVE TO download them. This is completely unpractical and I do not understand why was it changed. It was useful especially when I navigate Instagram for example, when I just want to take the clean image and not download it immediately. 

Can I somehow use the previous version?

**Comment by eight04** [comment]
Well, I didn't expect that someone uses this extension as a simple image viewer. Starting from 0.8, images are displayed in buttons which probably causes this issue.

> right click on the images and then have the option to View Image, Open Image in Tab, Search By Image, etc...

This is definitely a regression. Users should be able to copy the image URL with the context menu.

> Can I somehow use the previous version?

You can download old versions from here:
https://addons.mozilla.org/en-US/firefox/addon/image-picka/versions/
