### ISSUE TITLE
When downloading from multiple tabs, pageTitle is incorrect

### ISSUE THREAD

**Issue by Thom-a-Anderson** [eight04/image-picka#99]
This is a very impressive add-on!  It explodes the S3 Download Manager when S3 is enabled, sadly, so I have to flip it on and off.

If I am downloading from six tabs - let's say tabs A..F - and downloading two images per page, I would expect the following files (using a ${pageTitle} - ${index} - ${name}${ext} format):

Page A - 01.jpg
Page A - 02.jpg
Page B - 01.jpg
Page B - 02.jpg 
etc.

Instead, I get

Page A - (1) - 01.jpg
Page A - (2) - 02.jpg
Page A - (3) - 01.jpg
Page A - (4) - 02.jpg
etc.

I think the pageTitle should be from the individual page when using multiple tabs.  And the index would be nicer if it was right-justified with leading zeros to avoid sorting issues.

- Tom

**Comment by eight04** [comment]
Enable "Isolate tabs from each other" option in the batch download settings.
